import type { PortalDomain, PortalRecord } from '@/types/portalFinal';
import type { PortalCommand } from '@/services/portalFinal.repository';
export interface FormField { key: string; label: string; type?: 'text'|'textarea'|'date'|'time'|'file'|'integer'|'money'|'select'; options?: string[]; optional?: boolean; max?: number }
export interface PortalAction { command: PortalCommand; label: string; permission: string; fields: FormField[]; keyed?: boolean; versioned?: boolean; states?: string[]; targetOnly?: boolean }
export interface PortalDefinition { title: string; permission: string; navigation?: string; description: string; fields: [keyof PortalRecord,string][]; detail: boolean; create?: PortalAction; actions: PortalAction[] }
const f=(key:string,label:string,type:FormField['type']='text',optional=false):FormField=>({key,label,type,optional});
const name=f('name','Name'),reason=f('reason','Reason','textarea'),file=f('file','File','file');
const announcement=[f('title','Title'),f('description','Description','textarea'),{...f('priority','Priority','select'),options:['LOW','NORMAL','HIGH']},f('expires_at','Expiry (ISO 8601 with offset)','text',true)];
const expense=[f('category_id','Expense category','select'),f('title','Title'),f('description','Description','textarea',true),f('amount_minor','Amount (PKR)','money'),f('expense_date','Expense date','date')];
const contact=[name,f('relationship','Relationship'),f('phone','Phone')];
const make=(command:PortalCommand,label:string,permission:string,fields:FormField[]=[],keyed=false,versioned=true,states?:string[]):PortalAction=>({command,label,permission,fields,keyed,versioned,states});
export function portalDefinition(domain: PortalDomain, admin: boolean): PortalDefinition {
  const base: PortalDefinition={title:'',permission:'',description:'',fields:[],detail:true,actions:[]};
  switch(domain){
    case 'documents': return {...base,title:admin?'Employee documents':'Documents',permission:admin?'employee.documents.admin.view':'employee.documents.view',navigation:admin?'hrm.employee_documents':'employee.documents',description:admin?'Issue a private document, then release it separately. Assignment is not release.':'Your personal uploads and released HR documents. No verification, replacement or deletion workflow.',fields:[['original_filename','Filename'],['category','Category'],['mime_type','Type'],['size_bytes','Bytes'],['created_at','Uploaded'],...(admin?[['employee_id','Employee'],['released_at','Released']] as [keyof PortalRecord,string][]:[])],create:make('create',admin?'Issue document':'Upload document',admin?'employee.documents.issue':'employee.documents.upload',admin?[f('employee_id','Employee UUID'),file]:[file],true,false),actions:admin?[make('release','Release to employee','employee.documents.release',[],false,false)]:[]};
    case 'announcements': return {...base,title:'Announcements',permission:admin?'announcements.view':'employee.announcements.view',navigation:admin?'hrm.announcements':'employee.announcements',description:'Company-wide announcements. Publication and expiry are controlled by the server; notifications use your existing inbox.',fields:[['title','Title'],['description','Description'],['priority','Priority'],['status','Publication state'],['published_at','Published'],['expires_at','Expiry']],create:admin?make('create','Create draft','announcements.manage',announcement,true,false):undefined,actions:admin?[make('edit','Edit draft','announcements.manage',announcement,false,true,['DRAFT']),make('attachment','Attach file','announcements.manage',[file],true,true,['DRAFT']),make('publish','Publish announcement','announcements.publish',[],false,true,['DRAFT'])]:[]};
    case 'contacts':return {...base,title:'Emergency contacts',permission:'employee.self.view',description:'Private emergency contacts for your own employee profile.',fields:[['name','Name'],['relationship','Relationship'],['phone','Phone']],create:make('create','Add contact','employee.profile.edit',contact,true,false),actions:[make('edit','Edit contact','employee.profile.edit',contact),make('remove','Remove contact','employee.profile.edit')]};
    case 'directory':return {...base,title:'Colleague directory',permission:'employee.directory.view',navigation:'employee.directory',description:'Current colleagues. Reporting relationships do not grant HR or Payroll access.',detail:false,fields:[['full_name','Name'],['department','Department'],['designation','Designation'],['location','Location']]};
    case 'direct-reports':return {...base,title:'Direct reports',permission:'employee.teams.view',description:'Explicit current reporting relationships.',detail:false,fields:[['full_name','Name'],['department','Department'],['designation','Designation'],['location','Location']]};
    case 'teams':return {...base,title:admin?'Teams':'My Team',permission:admin?'teams.view':'employee.teams.view',navigation:admin?'hrm.teams':'employee.teams',description:'Explicit team membership and reporting relationships. Department alone is not a team.',fields:[['name','Name'],['member_count','Members']],create:admin?make('create','Create team','teams.manage',[name],true,false):undefined,actions:admin?[make('edit','Rename team','teams.manage',[name]),make('members','Add member','teams.manage',[f('employee_id','Employee UUID')]),make('remove-member','Remove member','teams.manage',[f('child_id','Member','select')]),make('lead','Set lead','teams.manage',[f('employee_id','Lead member (blank removes lead)','select',true)])]:[]};
    case 'schedule':return {...base,title:'Published schedule',permission:'employee.schedule.view',navigation:'employee.schedule',description:'Only your published assignments. Times are company-local; no attendance, overtime or Payroll effects are inferred.',detail:false,fields:[['shift_name','Shift'],['shift_date','Date'],['start_time','Start'],['end_time','End'],['timezone','Company timezone'],['id','Assignment reference']]};
    case 'swaps':return {...base,title:'Shift swaps',permission:admin?'schedules.view':'employee.schedule.view',navigation:admin?'hrm.shift_swaps':'employee.shift_swaps',description:'Target consent comes before a separate administrator decision. Assignment exchange occurs only after server approval.',fields:[['from_assignment_id','Requested assignment'],['to_assignment_id','Target assignment'],['status','Status'],['reason','Reason'],['target_accepted_at','Target accepted'],['decision_reason','Decision reason'],['decided_at','Decided']],create:admin?undefined:make('create','Request swap','employee.schedule.swap.request',[f('from_assignment_id','Your assignment UUID'),f('to_assignment_id','Target assignment UUID (shared by colleague)'),reason],true,false),actions:admin?[make('approve','Approve exchange','schedules.swaps.decide',[],false,true,['PENDING_ADMIN']),make('reject','Reject exchange','schedules.swaps.decide',[reason],false,true,['PENDING_ADMIN'])]:[ {...make('accept','Accept swap','employee.schedule.swap.respond',[],false,true,['PENDING_TARGET']),targetOnly:true},{...make('decline','Decline swap','employee.schedule.swap.respond',[],false,true,['PENDING_TARGET']),targetOnly:true}]};
    case 'assets':return {...base,title:'Equipment requests',permission:admin?'assets.view':'employee.assets.view',navigation:admin?'hrm.asset_requests':'employee.assets',description:'New equipment requests only. Approved does not mean issued. Custody, stock fulfilment, returns and damage reports are unavailable.',fields:[['item_description','Requested equipment'],['reason','Reason'],['type','Request type'],['status','Request status'],['decision_reason','Decision reason'],['created_at','Requested'],['decided_at','Decided']],create:admin?undefined:make('create','Request equipment','employee.assets.request',[f('item_description','Equipment description'),reason],true,false),actions:admin?[make('approve','Approve request','assets.decide',[],false,true,['PENDING']),make('reject','Reject request','assets.decide',[reason],false,true,['PENDING'])]:[]};
    case 'expenses':return {...base,title:'Expense claims',permission:admin?'expenses.view':'employee.expenses.view',navigation:admin?'hrm.expenses':'employee.expenses',description:'Draft, attach a receipt and submit for review. Approved does not mean paid. Payment, Banking and Accounting integration are unavailable.',fields:[['title','Title'],['description','Description'],['category_id','Category reference'],['amount_minor','Amount (PKR)'],['expense_date','Expense date'],['status','Claim status'],['submitted_at','Submitted'],['decision_reason','Decision reason'],['decided_at','Decided']],create:admin?undefined:make('create','Create claim','employee.expenses.create',expense,true,false),actions:admin?[make('approve','Approve claim','expenses.approve',[],false,true,['SUBMITTED']),make('reject','Reject claim','expenses.approve',[reason],false,true,['SUBMITTED'])]:[make('edit','Edit draft','employee.expenses.edit',expense,false,true,['DRAFT']),make('receipt','Attach receipt','employee.expenses.edit',[file],true,true,['DRAFT']),make('submit','Submit claim','employee.expenses.submit',[],false,true,['DRAFT'])]};
    case 'categories':return {...base,title:'Expense categories',permission:admin?'expenses.view':'employee.expenses.view',navigation:admin?'hrm.expense_categories':undefined,description:'Only active categories are available for new claims.',detail:false,fields:[['name','Name'],['is_active','Active']],create:admin?make('create','Create category','expenses.categories.manage',[name],true,false):undefined,actions:admin?[make('active','Change availability','expenses.categories.manage',[{...f('is_active','Active','select'),options:['true','false']}])]:[]};
    case 'shifts':return {...base,title:'Shifts',permission:'schedules.view',navigation:'hrm.shifts',description:'Day shifts only. End must follow start on the same company-local date.',detail:false,fields:[['name','Name'],['start_time','Start'],['end_time','End'],['is_active','Active']],create:make('create','Create shift','schedules.manage',[name,f('start_time','Start time','time'),f('end_time','End time','time')],true,false)};
    case 'rotas':return {...base,title:'Rotas',permission:'schedules.view',navigation:'hrm.rotas',description:'Create a period, add shift slots and assignments, then explicitly publish. Required coverage is a minimum target.',fields:[['name','Name'],['start_date','Start date'],['end_date','End date'],['timezone','Company timezone'],['status','Status'],['published_at','Published']],create:make('create','Create rota','schedules.manage',[name,f('start_date','Start date','date'),f('end_date','End date','date')],true,false),actions:[make('slots','Add slot','schedules.manage',[f('shift_id','Shift UUID'),f('shift_date','Shift date','date'),f('required_coverage','Required coverage','integer')],true,false,['DRAFT']),make('assignment','Assign employee','schedules.manage',[f('child_id','Slot','select'),f('employee_id','Employee UUID')],true,false),make('publish','Publish rota','schedules.manage',[],false,true,['DRAFT'])]};
  }
}
export function minorToDecimal(value: number): string {
  if (!Number.isSafeInteger(value) || value < 0) return 'Unavailable';
  const n=BigInt(value);return `${n/100n}.${String(n%100n).padStart(2,'0')}`;
}
export function decimalToMinor(value: string): number {
  if (!/^\d+(\.\d{1,2})?$/.test(value)) throw new Error('Enter a positive PKR amount with at most two decimal places.');
  const [whole,part='']=value.split('.');const n=BigInt(whole!)*100n+BigInt(part.padEnd(2,'0'));
  if(n<1n||n>999999999999999n)throw new Error('Amount must be positive and within the certified limit.');return Number(n);
}
