import type { CrmActivity, CrmCompany, CrmContact, CrmLead, CrmTask, EmailEvent, EmailIntegration, LeadStage, Sequence, CrmDeal } from '@/types/crm'
const owners=['Ayesha Khan','Bilal Ahmed','Sara Malik','Usman Tariq']; const stages:LeadStage[]=['New','Contacted','Qualified','Proposal','Negotiation','Won','Lost'];
const accounts=['Nexa Retail','PakTek Industries','GreenLine Foods','Vertex Logistics','Medora Health','BluePeak Energy','Crescent Textiles','Orbit Learning'];
const industries=['Retail','Manufacturing','Food & Beverage','Logistics','Healthcare','Energy','Textiles','Education'];
export const crmCompanies:CrmCompany[]=accounts.flatMap((name,i)=>['c1','c2','c3'].map((companyId,j)=>({id:`co-${companyId}-${i}`,companyId,name:j?`${name} ${j+1}`:name,industry:industries[i]!,website:`https://${name.toLowerCase().replaceAll(' ','')}.pk`,primaryContact:['Hira Iqbal','Omar Shah','Maham Ali','Zain Raza'][i%4]!,phone:`+92 300 ${1200000+i*7311}`,email:`hello@${name.toLowerCase().replaceAll(' ','')}.pk`,status:i%5===0?'Prospect':'Active',owner:owners[i%4]!,lastActivity:`2026-09-${String(21-i).padStart(2,'0')}`,size:['11–50','51–200','201–500'][i%3]!,revenue:['PKR 80M–150M','PKR 150M–500M','PKR 500M+'][i%3]!,address:`${20+i}, Shahrah-e-Faisal, Karachi`,source:['Referral','Website','Event'][i%3]!})));
export const crmContacts:CrmContact[]=Array.from({length:16},(_,i)=>{const a=crmCompanies[i%8]!;return{id:`ct-${a.companyId}-${i}`,companyId:a.companyId,name:['Hira Iqbal','Omar Shah','Maham Ali','Zain Raza','Noor Fatima','Hamza Qureshi','Sana Aslam','Ali Nawaz'][i%8]!,accountId:a.id,company:a.name,title:['CFO','Head of Operations','HR Director','Finance Manager'][i%4]!,email:`contact${i+1}@example.pk`,phone:`+92 321 ${4500000+i*117}`,linkedin:`linkedin.com/in/contact-${i+1}`,owner:owners[i%4]!,status:i%6===0?'Inactive':'Active',lastActivity:`2026-09-${String(22-i%12).padStart(2,'0')}`}})
export const crmLeads:CrmLead[]=Array.from({length:21},(_,i)=>{const a=crmCompanies[i%8]!;const fit=28+(i*7)%43,intent=12+(i*11)%39,total=Math.min(100,fit+intent);return{id:`ld-${a.companyId}-${i}`,companyId:a.companyId,firstName:['Hira','Omar','Maham','Zain','Noor','Hamza','Sana'][i%7]!,lastName:['Iqbal','Shah','Ali','Raza','Fatima','Qureshi','Aslam'][i%7]!,name:`${['Hira','Omar','Maham','Zain','Noor','Hamza','Sana'][i%7]} ${['Iqbal','Shah','Ali','Raza','Fatima','Qureshi','Aslam'][i%7]}`,company:a.name,accountId:a.id,title:['CFO','COO','HR Director','Finance Manager'][i%4]!,email:`lead${i+1}@example.pk`,phone:`+92 333 ${7100000+i*101}`,website:a.website,linkedin:`linkedin.com/in/lead-${i+1}`,industry:a.industry,size:a.size,source:['Website','Referral','Conference','CSV Import'][i%4]!,stage:stages[i%7]!,value:1500000+i*375000,score:{fit,intent,total,heat:total>=75?'Hot':total>=50?'Warm':'Cold'},owner:owners[i%4]!,lastActivity:`2026-09-${String(22-i%14).padStart(2,'0')}`,notes:'Interested in consolidating finance and people operations.',enrichment:{state:i%4===0?'not_enriched':'enriched',summary:`${a.name} is a growing ${a.industry.toLowerCase()} business modernizing its operating systems.`,industry:a.industry,size:a.size,profile:'Privately held Pakistan-based growth company with distributed teams.',painPoints:['Manual reporting','Disconnected customer data'],opportunities:['Unified ERP rollout','Automated finance workflows'],valueProposition:'Reduce administrative work while improving decision visibility.',sources:[a.website,'LinkedIn company profile'],enrichedAt:i%4===0?undefined:'2026-09-20 14:30'}}})
export const crmActivities:CrmActivity[]=Array.from({length:22},(_,i)=>{const l=crmLeads[i%crmLeads.length]!;const type=(['Email','Call','Note','Task','Meeting','Stage change','AI enrichment','Outreach'] as const)[i%8]!;return{id:`ac-${i}`,companyId:l.companyId,leadId:l.id,accountId:l.accountId,type,title:`${type}: ${l.company}`,detail:['Pricing overview shared','Discovery call completed','Implementation requirements captured','Follow-up assigned'][i%4]!,actor:owners[i%4]!,timestamp:`2026-09-${String(22-i%15).padStart(2,'0')} ${String(9+i%8).padStart(2,'0')}:30`,status:i%3===0?'Completed':undefined}})
export const crmTasks:CrmTask[]=Array.from({length:12},(_,i)=>{const l=crmLeads[i]!;return{id:`tk-${i}`,companyId:l.companyId,title:['Send implementation brief','Schedule discovery call','Review pricing request','Confirm decision makers'][i%4]!,relatedTo:l.company,owner:owners[i%4]!,due:`2026-09-${String(22+i%8).padStart(2,'0')}`,priority:(['High','Medium','Low'] as const)[i%3]!,status:(['Open','In progress','Completed'] as const)[i%3]!}})
export const emailEvents:EmailEvent[]=crmLeads.slice(0,10).flatMap((l,i)=>[{id:`em-${i}-1`,companyId:l.companyId,leadId:l.id,date:`2026-09-${18+i%5} 10:20`,subject:`A simpler operating system for ${l.company}`,sequence:'Operational efficiency',status:i%3===0?'Replied':'Opened',sender:'ayesha@zavsync.com',step:1,body:`Hi ${l.firstName},\n\nI noticed ${l.company} is growing its operations. ZavSync can connect your finance, people, and customer workflows in one place.\n\nWould a short walkthrough be useful?`},{id:`em-${i}-2`,companyId:l.companyId,leadId:l.id,date:`2026-09-${20+i%3} 09:15`,subject:'A quick follow-up',sequence:'Operational efficiency',status:'Follow-up sent',sender:'ayesha@zavsync.com',step:2,body:`Hi ${l.firstName},\n\nFollowing up with a concise overview tailored to ${l.company}. Happy to share examples from ${l.industry}.`}])
export const sequences:Sequence[]=crmLeads.slice(0,5).map((l,i)=>({id:`sq-${i}`,companyId:l.companyId,name:['Operational efficiency','Finance modernization','HR workflow review'][i%3]!,objective:'Book a qualified discovery call',tone:i%2?'Professional':'Consultative',leadId:l.id,steps:[{id:'s1',subject:`A simpler operating system for ${l.company}`,body:`Hi ${l.firstName},\n\nI prepared a few ideas for ${l.company}.`,delayDays:0},{id:'s2',subject:'A quick follow-up',body:`Hi ${l.firstName},\n\nWould a 20-minute walkthrough be useful?`,delayDays:3},{id:'s3',subject:'Should I close the loop?',body:`Hi ${l.firstName},\n\nHappy to reconnect when the timing is better.`,delayDays:5}],status:(['Active','Draft','Paused','Completed'] as const)[i%4]!,enrolled:18+i*7,completed:6+i*2,replied:2+i,openRate:62+i*4,replyRate:12+i*2}))
export const integrations:EmailIntegration[]=[{id:'gmail',companyId:'c1',provider:'Gmail',email:'sales@zavsync.com',status:'Connected',lastSync:'2026-09-22 05:10'},{id:'outlook',companyId:'c1',provider:'Microsoft Outlook',email:'',status:'Not Connected'}]

export const crmDeals:CrmDeal[]=crmLeads.slice(0,15).map((l,i)=>({id:`deal-${l.companyId}-${i}`,companyId:l.companyId,name:[`ERP rollout — ${l.company}`,`Finance modernization — ${l.company}`,`People operations — ${l.company}`][i%3]!,accountId:l.accountId,company:l.company,contact:l.name,stage:(['Qualified','Proposal','Negotiation','Won','Lost'] as LeadStage[])[i%5]!,value:l.value*2,probability:[30,50,70,100,0][i%5]!,expectedClose:`2026-${String(10+i%3).padStart(2,'0')}-${String(10+i%17).padStart(2,'0')}`,owner:l.owner,source:l.source,nextStep:['Discovery workshop','Commercial proposal','Legal review','Handover to delivery','Close reason review'][i%5]!,lastActivity:l.lastActivity}))
