import { apiRequest } from "@/services/api/client";
import type { BankAccount, BankTransaction, CashForecast, Settlement } from "@/types/operations";
export const operationsRepository={
 async bankAccounts(companyId:string){const rows=await apiRequest<Array<{id:string;name:string;type:"bank"|"cash";bank_name:string|null;masked_account_number:string|null;currency:string;gl_account_id:string;book_balance:number;statement_balance:number|null;is_default:boolean;is_active:boolean}>>("/banking/accounts",{companyId});return rows.map((x):BankAccount=>({id:x.id,company_id:companyId,name:x.name,institution:x.bank_name??(x.type==="cash"?"Cash account":"Bank"),masked_number:x.masked_account_number??"—",type:x.type,currency:x.currency,balance:x.book_balance,available:x.book_balance,statement_balance:x.statement_balance,gl_account_id:x.gl_account_id,is_default:x.is_default,status:x.is_active?"active":"inactive"}))},
 createBankAccount(companyId:string,input:{name:string;type:"bank"|"cash";bank_name:string|null;currency:string;gl_account_id:string;is_default:boolean}){return apiRequest("/banking/accounts",{method:"POST",companyId,body:{...input,account_title:null,masked_account_number:null,iban:null,opening_balance:null,is_active:true,notes:null}})},
 updateBankAccount(companyId:string,id:string,input:{name:string;type:"bank"|"cash";bank_name:string|null;currency:string;gl_account_id:string;is_default:boolean;is_active:boolean}){return apiRequest(`/banking/accounts/${id}`,{method:"PATCH",companyId,body:{...input,account_title:null,masked_account_number:null,iban:null,opening_balance:null,notes:null}})},
 async bankTransactions(companyId:string){const payload=await apiRequest<{data:Array<{id:string;transaction_date:string;description:string;bank_reference:string|null;amount:number;direction:"credit"|"debit";status:BankTransaction["status"]}>}>("/banking/transactions",{companyId});return payload.data.map((x):BankTransaction=>({id:x.id,company_id:companyId,date:x.transaction_date,description:x.description,reference:x.bank_reference??"—",amount:x.amount,direction:x.direction==="credit"?"in":"out",status:x.status}))},
 async transactionSuggestions(companyId:string,id:string){return apiRequest<{data:Array<{type:string;id:string;reference:string;date:string;amount:number;party:string|null;confidence:"exact"|"high"|"possible";reason:string;score:number}>}>(`/banking/transactions/${id}/suggestions`,{companyId})},
 async matchTransaction(companyId:string,transactionId:string,candidate:{type:string;id:string;amount:number}){return apiRequest(`/banking/transactions/${transactionId}/match`,{method:"POST",companyId,idempotencyKey:crypto.randomUUID(),body:{matchable_type:candidate.type,matchable_id:candidate.id,amount:candidate.amount,confidence:"manual"}})},
 classifyTransaction(companyId:string,transactionId:string,counterpartAccountId:string,description:string){return apiRequest(`/banking/transactions/${transactionId}/classify`,{method:"POST",companyId,idempotencyKey:crypto.randomUUID(),body:{counterpart_account_id:counterpartAccountId,description}})},
 async importStatement(companyId:string,financialAccountId:string,file:File){const body=new FormData();body.set("financial_account_id",financialAccountId);body.set("file",file);return apiRequest<{id:string;row_count:number;preview_rows:Array<Record<string,unknown>>}>("/banking/statement-imports/preview",{method:"POST",companyId,idempotencyKey:crypto.randomUUID(),body})},
 confirmStatement(companyId:string,id:string){return apiRequest(`/banking/statement-imports/${id}/confirm`,{method:"POST",companyId,idempotencyKey:crypto.randomUUID(),body:{}})},
 async settlements(companyId:string){const rows=await apiRequest<Array<{id:string;provider:string;settlement_reference:string;settlement_date:string;gross_amount:number;fee_amount:number;adjustment_amount:number;net_amount:number;status:Settlement["status"];destination_account?:{name:string}}>>("/banking/settlements",{companyId});return rows.map((x):Settlement=>({id:x.id,company_id:companyId,provider:x.provider,reference:x.settlement_reference,date:x.settlement_date,gross:x.gross_amount,fees:x.fee_amount,adjustments:x.adjustment_amount,net:x.net_amount,status:x.status,bank_account:x.destination_account?.name??"—"}))},
 createSettlement(companyId:string,input:{provider:string;settlement_reference:string;settlement_date:string;gross_amount:number;fee_amount:number;adjustment_amount:number;net_amount:number;destination_financial_account_id:string;clearing_account_id:string;fee_account_id:string}){return apiRequest("/banking/settlements",{method:"POST",companyId,idempotencyKey:crypto.randomUUID(),body:{...input,currency:"PKR",post:true,allocations:[]}})},
 cashForecast:(companyId:string,horizon:7|30|60|90)=>apiRequest<CashForecast>("/banking/cash-forecast",{companyId,query:{horizon}}),
 bankGl:(companyId:string,financialAccountId:string)=>apiRequest<{statement_balance:number|null;book_balance:number;unmatched_credits:number;unmatched_debits:number;difference:number|null;status:"balanced"|"unbalanced"}>(`/banking/accounts/${financialAccountId}/bank-gl`,{companyId}),
};
