import { apiRequest,isApiConfigured,previewDelay,validationError } from "@/services/api/client";
import { auditEvents,bankAccounts,bankTransactions,budgets,copilotActions,expenses,knowledgeDocuments,purchaseOrders,recommendations,settlements } from "./mock-db";
import type { AuditEvent,BankAccount,BankTransaction,BudgetLine,CopilotAction,ExpenseClaim,KnowledgeDocument,PurchaseOrder,Recommendation,Settlement } from "@/types/operations";
const scoped=<T extends {company_id:string}>(rows:T[],id:string)=>rows.filter(r=>r.company_id===id);
async function list<T extends {company_id:string}>(companyId:string,path:string,rows:T[]){return isApiConfigured()?apiRequest<T[]>(path,{companyId}):previewDelay(scoped(rows,companyId));}
export const operationsRepository={
 purchaseOrders:(id:string)=>list<PurchaseOrder>(id,"/purchases/orders",purchaseOrders), expenses:(id:string)=>list<ExpenseClaim>(id,"/expenses",expenses), bankAccounts:(id:string)=>list<BankAccount>(id,"/banking/accounts",bankAccounts), bankTransactions:(id:string)=>list<BankTransaction>(id,"/banking/transactions",bankTransactions), settlements:(id:string)=>list<Settlement>(id,"/banking/settlements",settlements), budgets:(id:string)=>list<BudgetLine>(id,"/budgets",budgets), audit:(id:string)=>list<AuditEvent>(id,"/audit-events",auditEvents), recommendations:(id:string)=>list<Recommendation>(id,"/ai/recommendations",recommendations), documents:(id:string)=>list<KnowledgeDocument>(id,"/knowledge/documents",knowledgeDocuments), copilot:(id:string)=>list<CopilotAction>(id,"/copilot/actions",copilotActions),
 async updateStatus<T extends {id:string;company_id:string;status:string}>(companyId:string,path:string,rows:T[],recordId:string,status:T["status"]){if(isApiConfigured())return apiRequest<T>(`${path}/${recordId}`,{method:"PATCH",companyId,body:{status}});const row=rows.find(x=>x.id===recordId&&x.company_id===companyId);if(!row)throw validationError("This record is unavailable in the active company.");row.status=status;return previewDelay(row);},
 updatePurchaseStatus(companyId:string,id:string,status:PurchaseOrder["status"]){return this.updateStatus(companyId,"/purchases/orders",purchaseOrders,id,status)}, updateExpenseStatus(companyId:string,id:string,status:ExpenseClaim["status"]){return this.updateStatus(companyId,"/expenses",expenses,id,status)}, updateRecommendation(companyId:string,id:string,status:Recommendation["status"]){return this.updateStatus(companyId,"/ai/recommendations",recommendations,id,status)}, updateTransaction(companyId:string,id:string,status:BankTransaction["status"]){return this.updateStatus(companyId,"/banking/transactions",bankTransactions,id,status)},
 async addDocument(companyId:string,name:string,type:KnowledgeDocument["type"]){const row:KnowledgeDocument={id:`${companyId}-doc-${Date.now()}`,company_id:companyId,name,type,owner:"Humza Mazhar",uploaded_at:new Date().toISOString(),size:"Pending",status:"processing",access:"Company users"};knowledgeDocuments.unshift(row);return previewDelay(row)},
 async addCopilot(companyId:string,action:Omit<CopilotAction,"id"|"company_id"|"created_at">){const row:CopilotAction={...action,id:`${companyId}-cop-${Date.now()}`,company_id:companyId,created_at:new Date().toISOString()};copilotActions.unshift(row);return previewDelay(row)}, updateCopilot(companyId:string,id:string,status:CopilotAction["status"]){return this.updateStatus(companyId,"/copilot/actions",copilotActions,id,status)},
};
