/**
 * Phase A — Core Accounting Engine domain types.
 *
 * MONEY: every monetary value in the accounting domain is an INTEGER number of
 * minor units (paisa for PKR). Never store or compute accounting amounts as
 * floats. Use the helpers in `@/lib/money` for arithmetic, parsing and display.
 *
 * COMPANY SCOPE: every record carries `company_id`. The repository layer refuses
 * to return records outside the active company.
 */

/** Integer minor units (e.g. 125050 = PKR 1,250.50). */
export type Money = number;

export interface CompanyScoped {
  company_id: string;
}

export interface AuditTrail {
  created_by: string;
  created_at: string;
  updated_by?: string | null;
  updated_at?: string | null;
}

/* ------------------------------------------------------------------ */
/* A1 — Chart of Accounts                                              */
/* ------------------------------------------------------------------ */

export type AccountType = "asset" | "liability" | "equity" | "revenue" | "expense";

export const ACCOUNT_TYPES: { value: AccountType; label: string; normal: "debit" | "credit" }[] = [
  { value: "asset", label: "Asset", normal: "debit" },
  { value: "liability", label: "Liability", normal: "credit" },
  { value: "equity", label: "Equity", normal: "credit" },
  { value: "revenue", label: "Revenue", normal: "credit" },
  { value: "expense", label: "Expense", normal: "debit" },
];

export interface Account extends CompanyScoped, AuditTrail {
  id: string;
  code: string;
  name: string;
  type: AccountType;
  parent_id: string | null;
  is_active: boolean;
  /** System/protected accounts (AR control, AP control, Inventory, COGS…). */
  is_system: boolean;
  description?: string;
  currency: string;
  opening_balance: Money;
  opening_balance_date: string | null;
  /** Backend-computed closing balance. Never derived authoritatively in the UI. */
  balance: Money;
  /** Backend-reported count of posted journal lines referencing this account. */
  transaction_count: number;
}

export interface AccountInput {
  code: string;
  name: string;
  type: AccountType;
  parent_id: string | null;
  is_active: boolean;
  description?: string;
  opening_balance: Money;
  opening_balance_date: string | null;
}

/** Flattened tree node used by the CoA table and the account selector. */
export interface AccountNode extends Account {
  depth: number;
  has_children: boolean;
}

/* ------------------------------------------------------------------ */
/* A2 / A6 — Periods, journals, general ledger                         */
/* ------------------------------------------------------------------ */

export type PeriodStatus = "open" | "closed";

export interface AccountingPeriod extends CompanyScoped {
  id: string;
  name: string;
  start_date: string;
  end_date: string;
  status: PeriodStatus;
  closed_by?: string | null;
  closed_at?: string | null;
}

export type JournalStatus = "draft" | "posted" | "reversed";

export type ReferenceType =
  | "invoice"
  | "customer_payment"
  | "supplier_bill"
  | "supplier_payment"
  | "inventory"
  | "payroll"
  | "manual_journal";

export const REFERENCE_TYPES: { value: ReferenceType; label: string }[] = [
  { value: "invoice", label: "Invoice" },
  { value: "customer_payment", label: "Customer Payment" },
  { value: "supplier_bill", label: "Supplier Bill" },
  { value: "supplier_payment", label: "Supplier Payment" },
  { value: "inventory", label: "Inventory" },
  { value: "payroll", label: "Payroll" },
  { value: "manual_journal", label: "Manual Journal" },
];

export interface JournalLine {
  id: string;
  account_id: string;
  account_code: string;
  account_name: string;
  description: string;
  debit: Money;
  credit: Money;
}

export interface JournalLineInput {
  id: string;
  account_id: string | null;
  description: string;
  debit: Money;
  credit: Money;
}

export interface Journal extends CompanyScoped, AuditTrail {
  id: string;
  number: string;
  posting_date: string;
  reference: string;
  reference_type: ReferenceType;
  /** Source record in the originating module, when generated by one. */
  source_id?: string | null;
  source_label?: string | null;
  source_route?: string | null;
  description: string;
  status: JournalStatus;
  lines: JournalLine[];
  total_debit: Money;
  total_credit: Money;
  posted_by?: string | null;
  posted_at?: string | null;
  /** Set on a correcting journal that reverses another. */
  reverses_journal_id?: string | null;
  /** Set on the original once reversed. */
  reversed_by_journal_id?: string | null;
}

export interface JournalInput {
  posting_date: string;
  reference: string;
  description: string;
  lines: JournalLineInput[];
}

export interface LedgerEntry extends CompanyScoped {
  id: string;
  posting_date: string;
  journal_id: string;
  journal_number: string;
  account_id: string;
  account_code: string;
  account_name: string;
  reference_type: ReferenceType;
  reference: string;
  description: string;
  debit: Money;
  credit: Money;
  /** Running balance supplied by the backend for the requested ordering. */
  running_balance: Money;
}

export interface LedgerResult {
  opening_balance: Money;
  closing_balance: Money;
  total_debit: Money;
  total_credit: Money;
  entries: LedgerEntry[];
}

export interface LedgerQuery {
  account_id?: string | null;
  from?: string;
  to?: string;
  reference_type?: ReferenceType | "all";
  reference?: string;
  search?: string;
}

/* ------------------------------------------------------------------ */
/* A3 — Accounts Receivable                                            */
/* ------------------------------------------------------------------ */

export type ReceivableStatus = "draft" | "unpaid" | "partial" | "paid" | "overdue" | "void";
export type InvoiceAccountingStatus = "draft" | "unpaid" | "partial" | "paid" | "void";
export type InvoiceFbrStatus = "not_submitted" | "pending" | "submitted" | "accepted" | "rejected" | "failed";

export interface Customer extends CompanyScoped {
  id: string;
  name: string;
  code: string;
  email: string;
  phone: string;
  tax_number: string;
  payment_terms_days: number;
  is_active: boolean;
  outstanding: Money;
  legal_name?: string | null;
  type?: "business" | "individual" | "government";
  ntn?: string | null;
  cnic?: string | null;
  strn?: string | null;
  billing_address?: string | null;
  city?: string | null;
  province?: string | null;
  country?: string;
  postal_code?: string | null;
  contact_person?: string | null;
  credit_limit?: Money | null;
  currency?: string;
  notes?: string | null;
}

export interface CustomerInput {
  name: string;
  legal_name?: string | null;
  type: "business" | "individual" | "government";
  ntn?: string | null;
  cnic?: string | null;
  strn?: string | null;
  email?: string | null;
  phone?: string | null;
  billing_address?: string | null;
  city?: string | null;
  province?: string | null;
  country: string;
  postal_code?: string | null;
  contact_person?: string | null;
  payment_terms_days: number;
  credit_limit?: Money | null;
  currency: string;
  is_active: boolean;
  notes?: string | null;
}

export interface ReceivableInvoice extends CompanyScoped, AuditTrail {
  id: string;
  invoice_number: string;
  customer_id: string;
  customer_name: string;
  invoice_date: string;
  due_date: string;
  currency: string;
  subtotal: Money;
  tax: Money;
  total: Money;
  paid_amount: Money;
  outstanding: Money;
  status: ReceivableStatus;
  days_overdue: number;
  journal_id?: string | null;
}

export interface InvoiceLineInput {
  item_id?: string | null;
  item_name?: string | null;
  description: string;
  quantity_milli: number;
  unit: string;
  unit_price: Money;
  discount: Money;
  tax_rate_bps: number;
  other_tax_rate_bps?: number;
  advance_tax_rate_bps?: number;
  withholding_tax_rate_bps?: number;
  sales_type: string;
  tax_metadata?: Record<string, unknown> | null;
}

export interface InvoiceInput {
  customer_id: string;
  invoice_date: string;
  due_date: string;
  currency: string;
  notes?: string | null;
  terms?: string | null;
  lines: InvoiceLineInput[];
}

export interface InvoiceLine extends InvoiceLineInput {
  id: string;
  position: number;
  subtotal: Money;
  taxable_amount: Money;
  tax_amount: Money;
  other_tax_amount: Money;
  advance_tax_amount: Money;
  withholding_tax_amount: Money;
  total: Money;
}

export interface InvoiceDetail extends ReceivableInvoice {
  accounting_status: InvoiceAccountingStatus;
  payment_status: ReceivableStatus;
  discount: Money;
  taxable_amount: Money;
  sales_tax: Money;
  other_tax: Money;
  advance_tax: Money;
  withholding_tax: Money;
  balance_due: Money;
  amount_paid: Money;
  balance: Money;
  notes: string | null;
  terms: string | null;
  fbr_status: InvoiceFbrStatus;
  fbr_reference_number: string | null;
  fbr_response_metadata: Record<string, unknown> | null;
  reversal_journal_id: string | null;
  lines?: InvoiceLine[];
  customer?: Customer;
  company?: { id: string; name: string; currency: string };
}

export type PaymentMethod = "bank_transfer" | "cash" | "cheque" | "card";

export interface PaymentInput {
  amount: Money;
  payment_date: string;
  posting_date?: string;
  method: PaymentMethod;
  bank_account_id: string | null;
  reference: string;
  note?: string;
}

export interface Payment extends CompanyScoped {
  id: string;
  number: string;
  party_id: string;
  party_name: string;
  document_id: string;
  document_number: string;
  payment_date: string;
  amount: Money;
  method: PaymentMethod;
  reference: string;
  journal_id?: string | null;
}

export type AgingBucketKey = "current" | "d1_30" | "d31_60" | "d61_90" | "d90_plus";

export const AGING_BUCKETS: { key: AgingBucketKey; label: string }[] = [
  { key: "current", label: "Current" },
  { key: "d1_30", label: "1–30 days" },
  { key: "d31_60", label: "31–60 days" },
  { key: "d61_90", label: "61–90 days" },
  { key: "d90_plus", label: "90+ days" },
];

export interface AgingRow {
  party_id: string;
  party_name: string;
  current: Money;
  d1_30: Money;
  d31_60: Money;
  d61_90: Money;
  d90_plus: Money;
  total: Money;
}

export interface StatementLine {
  id: string;
  date: string;
  type: "invoice" | "payment" | "credit_note" | "bill" | "bill_void";
  reference: string;
  description: string;
  debit: Money;
  credit: Money;
  balance: Money;
}

export interface Statement {
  party_id: string;
  party_name: string;
  from: string;
  to: string;
  opening_balance: Money;
  closing_balance: Money;
  lines: StatementLine[];
}

/* ------------------------------------------------------------------ */
/* A4 — Accounts Payable                                               */
/* ------------------------------------------------------------------ */

export type SupplierStatus = "active" | "inactive";

export interface Supplier extends CompanyScoped, AuditTrail {
  id: string;
  name: string;
  code: string;
  tax_number: string;
  email: string;
  phone: string;
  address: string;
  payment_terms_days: number;
  default_expense_account_id: string | null;
  default_payable_account_id: string | null;
  status: SupplierStatus;
  outstanding: Money;
}

export interface SupplierInput {
  name: string;
  tax_number: string;
  email: string;
  phone: string;
  address: string;
  payment_terms_days: number;
  default_expense_account_id: string | null;
  default_payable_account_id: string | null;
  status: SupplierStatus;
}

export interface SupplierBillLineInput {
  purchase_order_line_id?: string | null;
  purchase_receipt_line_id?: string | null;
  item_id?: string | null;
  item_name?: string | null;
  description: string;
  procurement_type: "goods" | "service";
  quantity_milli: number;
  unit: string;
  unit_price: Money;
  discount?: Money;
  tax_rate_bps?: number;
  withholding_rate_bps?: number;
  expense_account_id: string;
}

export interface SupplierBillInput {
  supplier_id: string;
  purchase_order_id?: string | null;
  purchase_receipt_id?: string | null;
  supplier_invoice_number: string;
  bill_date: string;
  posting_date: string;
  due_date: string;
  currency: string;
  notes?: string | null;
  lines: SupplierBillLineInput[];
}

export type BillStatus = "draft" | "unpaid" | "partial" | "paid" | "overdue" | "void";

export interface SupplierBill extends CompanyScoped, AuditTrail {
  id: string;
  bill_number: string;
  supplier_id: string;
  supplier_name: string;
  bill_date: string;
  due_date: string;
  posting_date?: string;
  reference: string;
  expense_account_id: string;
  expense_account_name: string;
  subtotal: Money;
  tax: Money;
  total: Money;
  paid_amount: Money;
  outstanding: Money;
  status: BillStatus;
  days_overdue: number;
  journal_id?: string | null;
  accounting_status?: "draft" | "unpaid" | "partial" | "paid" | "void";
  purchase_order_id?: string | null;
  purchase_receipt_id?: string | null;
}

/* ------------------------------------------------------------------ */
/* A5 — Inventory ledger & FIFO valuation                              */
/* ------------------------------------------------------------------ */

export type InventoryTxnType =
  | "purchase_receipt"
  | "sale_issue"
  | "customer_return"
  | "supplier_return"
  | "transfer_out"
  | "transfer_in"
  | "positive_adjustment"
  | "negative_adjustment"
  | "cost_adjustment";

export interface InventoryLedgerEntry extends CompanyScoped {
  id: string;
  item_id: string;
  item_name: string;
  item_sku: string;
  warehouse_id: string;
  warehouse: string;
  date: string;
  type: InventoryTxnType;
  reference: string;
  reference_type: ReferenceType;
  quantity_in: number;
  quantity_out: number;
  /** Backend-computed FIFO unit cost for the movement. */
  unit_cost: Money | null;
  /** Backend-computed value of the movement. */
  value: Money;
  running_quantity: number;
  running_value: Money;
  journal_id?: string | null;
}

export interface FifoLayer {
  id: string;
  item_id: string;
  item_sku: string;
  item_name: string;
  warehouse_id: string;
  warehouse: string;
  received_date: string;
  reference: string;
  original_quantity: number;
  remaining_quantity: number;
  unit_cost: Money;
  remaining_value: Money;
  age_days: number;
}

export interface FifoConsumption {
  layer_id: string;
  received_date: string;
  quantity: number;
  unit_cost: Money;
  value: Money;
}

export interface CogsPosting extends CompanyScoped {
  id: string;
  date: string;
  item_id: string;
  item_name: string;
  reference: string;
  quantity: number;
  cogs_amount: Money;
  consumption: FifoConsumption[];
  journal_id: string | null;
  posted: boolean;
}

export interface InventoryItemValuation extends CompanyScoped {
  id: string;
  sku: string;
  name: string;
  item_id: string;
  category: string | null;
  warehouse_id: string;
  warehouse: string;
  quantity: number;
  quantity_on_hand_milli: number;
  /** FIFO value from the backend valuation engine. */
  value: Money;
  average_unit_cost: Money;
  inventory_value: Money;
}

export type InventoryItemType = "inventory" | "non_inventory" | "service";

export interface InventoryItem extends CompanyScoped, AuditTrail {
  id: string;
  sku: string;
  name: string;
  description: string | null;
  type: InventoryItemType;
  track_inventory: boolean;
  unit: string;
  sales_unit: string | null;
  purchase_unit: string | null;
  category: string | null;
  barcode: string | null;
  is_active: boolean;
  sales_price: Money;
  default_purchase_cost: Money;
  reorder_level_milli: number;
  reorder_quantity_milli: number;
  inventory_asset_account_id: string | null;
  cogs_account_id: string | null;
  sales_account_id: string | null;
  inventory_adjustment_account_id: string | null;
  quantity_on_hand_milli: number;
  inventory_value: Money;
}

export interface InventoryItemInput {
  sku: string;
  name: string;
  description?: string | null;
  type: InventoryItemType;
  track_inventory: boolean;
  unit: string;
  sales_unit?: string | null;
  purchase_unit?: string | null;
  category?: string | null;
  barcode?: string | null;
  is_active: boolean;
  sales_price: Money;
  default_purchase_cost: Money;
  reorder_level_milli: number;
  reorder_quantity_milli: number;
  inventory_asset_account_id: string | null;
  cogs_account_id: string | null;
  sales_account_id: string | null;
  inventory_adjustment_account_id: string | null;
}

export interface Warehouse extends CompanyScoped, AuditTrail {
  id: string;
  code: string;
  name: string;
  location: string | null;
  is_active: boolean;
  is_default: boolean;
  quantity_on_hand_milli: number;
  inventory_value: Money;
}

export interface WarehouseInput {
  code: string;
  name: string;
  location?: string | null;
  is_active: boolean;
  is_default: boolean;
}

export interface InventoryTransaction extends CompanyScoped {
  id: string;
  number: string;
  type: InventoryTxnType;
  transaction_date: string;
  source_warehouse_id: string | null;
  destination_warehouse_id: string | null;
  reference: string | null;
  reason: string | null;
  journal_id: string | null;
}

export interface LowStockItem {
  id: string;
  sku: string;
  name: string;
  quantity_on_hand_milli: number;
  reorder_level_milli: number;
  reorder_quantity_milli: number;
  status: "low_stock" | "out_of_stock";
}

export interface InventoryReconciliation {
  as_of: string;
  inventory_valuation: Money;
  gl_inventory_balance: Money;
  difference: Money;
  status: "reconciled" | "difference";
  explanation: string;
}

/* ------------------------------------------------------------------ */
/* A7 — Payroll posting integration                                    */
/* ------------------------------------------------------------------ */

export type PayrollAccountingStatus = "not_posted" | "posted" | "reversed";

export interface PayrollPostingLine {
  label: string;
  account_id: string | null;
  account_code: string | null;
  account_name: string | null;
  debit: Money;
  credit: Money;
}

export interface PayrollPosting extends CompanyScoped {
  id: string;
  run_id: string;
  run_label: string;
  period: string;
  pay_date: string;
  employees: number;
  gross: Money;
  deductions: Money;
  employer_contributions: Money;
  net_pay: Money;
  accounting_status: PayrollAccountingStatus;
  posting_date: string | null;
  journal_id: string | null;
  journal_number: string | null;
  locked: boolean;
  preview: PayrollPostingLine[];
}

/** Configurable per-company mapping — never hard-code jurisdiction accounts. */
export type AccountMappingKey =
  | "accounts_receivable"
  | "accounts_payable"
  | "bank"
  | "cash"
  | "sales_revenue"
  | "sales_tax_payable"
  | "other_tax_payable"
  | "advance_tax_payable"
  | "withholding_tax_receivable"
  | "purchase_expense"
  | "purchase_tax_recoverable"
  | "withholding_tax_payable"
  | "input_tax"
  | "inventory_asset"
  | "cogs"
  | "inventory_adjustment"
  | "salary_expense"
  | "salary_payable"
  | "employer_contribution_expense"
  | "employer_contribution_payable"
  | "payroll_tax_payable";

export interface AccountMapping extends CompanyScoped {
  key: AccountMappingKey;
  label: string;
  description: string;
  account_id: string | null;
  required: boolean;
}
