import type { Money } from "@/types/accounting";
export type WorkflowStatus = "draft"|"pending"|"approved"|"rejected"|"cancelled"|"executed"|"paid"|"partially_received"|"received"|"matched"|"unmatched"|"processing"|"indexed"|"failed";
export interface CompanyRecord { id:string; company_id:string }
export interface PurchaseOrderLine { id:string; description:string; procurement_type:"goods"|"service"; quantity_milli:number; received_quantity_milli:number; billed_quantity_milli:number; unit:string; unit_price:Money; discount:Money; tax_rate_bps:number; total:Money; expense_account_id:string|null }
export interface PurchaseOrder extends CompanyRecord { number:string; supplier_id:string; supplier:string; date:string; expected_date:string|null; created_by:string; status:WorkflowStatus; subtotal:Money; discount:Money; tax:Money; total:Money; received:number; lines:PurchaseOrderLine[] }
export interface PurchaseOrderInput { supplier_id:string; order_date:string; expected_delivery_date?:string|null; currency:string; reference?:string|null; notes?:string|null; lines:{description:string;procurement_type:"goods"|"service";quantity_milli:number;unit:string;unit_price:Money;discount?:Money;tax_rate_bps?:number;expense_account_id?:string|null}[] }
export interface PurchaseReceipt extends CompanyRecord { purchase_order_id:string; supplier_id:string; warehouse_id:string|null; warehouse_name:string|null; inventory_status:"stocked"|"pending"|"not_applicable"; inventory_transaction_id:string|null; number:string; receipt_date:string; status:"partial"|"complete"; notes:string|null }
export interface ExpenseClaim extends CompanyRecord { reference:string; claimant:string; category:string; date:string; amount:Money; status:WorkflowStatus; receipt:boolean; notes:string }
export interface BankAccount extends CompanyRecord { name:string; institution:string; masked_number:string; type:"bank"|"cash"; currency:string; balance:Money; available:Money; statement_balance:Money|null; gl_account_id:string; is_default:boolean; status:"active"|"inactive" }
export interface BankTransaction extends CompanyRecord { date:string; description:string; reference:string; amount:Money; direction:"in"|"out"; status:"matched"|"suggested"|"unmatched"|"partially_matched"|"classified"|"ignored"; match_reference?:string; match_type?:string; confidence?:number }
export interface Settlement extends CompanyRecord { provider:string; reference:string; date:string; gross:Money; fees:Money; adjustments:Money; net:Money; status:"draft"|"posted"|"matched"; bank_account:string }
export interface CashForecast { as_of:string; horizon_days:7|30|60|90; through:string; current_cash:Money; expected_inflows:Money; expected_outflows:Money; projected_cash:Money; accounts:Array<{id:string;name:string;type:"bank"|"cash";currency:string;book_balance:Money;statement_balance:Money|null}>; inflows:Array<{id:string;number:string;party:string;due_date:string;amount:Money}>; outflows:Array<{id:string;number:string;party:string;due_date:string;amount:Money}> }
export interface AuditEvent extends CompanyRecord { timestamp:string; user:string; module:string; action:string; record:string; result:"success"|"denied"; before?:string; after?:string }
export interface Recommendation extends CompanyRecord { title:string; detail:string; module:string; impact:"low"|"medium"|"high"; status:"suggested"|"pending"|"approved"|"executed"|"rejected"; due?:string }
export interface KnowledgeDocument extends CompanyRecord { name:string; type:"PDF"|"Word"|"Excel"|"SOP"; owner:string; uploaded_at:string; size:string; status:"uploading"|"processing"|"indexed"|"failed"; access:string }
export interface CopilotAction extends CompanyRecord { command:string; intent:"record_revenue"|"create_invoice"|"add_employee"; summary:string; status:"preview"|"approved"|"executed"|"rejected"; amount?:Money; warnings:string[]; fields:Record<string,string>; created_at:string }
