export type ProviderType = "SMTP" | "GOOGLE" | "MICROSOFT";
export type ConnectionStatus = "DISCONNECTED" | "CONNECTED" | "ERROR" | "EXPIRED";
export type SequenceStatus = "DRAFT" | "ACTIVE" | "PAUSED" | "COMPLETED" | "ARCHIVED";
export type MessageState = "SCHEDULED" | "QUEUED" | "SENDING" | "SENT" | "DELIVERED" | "BOUNCED" | "FAILED" | "CANCELLED" | "SUPPRESSED";

export interface OutreachConnection { id:string; company_id:string; name:string; provider_type:ProviderType; status:ConnectionStatus; credentials_configured:boolean; token_expires_at:string|null; last_verified_at:string|null; last_error:string|null; identities_count?:number; created_at:string; updated_at:string }
export interface SendingIdentity { id:string; company_id:string; provider_connection_id:string; connection_name?:string; from_email:string; from_name:string; reply_to_email:string|null; verification_status:"PENDING"|"VERIFIED"|"FAILED"; is_default:boolean; is_active:boolean; verified_at:string|null; created_at:string }
export interface EmailTemplate { id:string; company_id:string; name:string; category:string; subject:string; body_html:string|null; body_text:string; allowed_variables:string[]; is_active:boolean; archived_at:string|null; created_at:string; updated_at:string }
export interface OutreachStep { id?:string; position?:number; type:"EMAIL"|"WAIT"; template_id?:string|null; subject?:string|null; body_html?:string|null; body_text?:string|null; wait_minutes:number }
export interface OutreachSequence { id:string; company_id:string; sending_identity_id:string; owner_id:number|null; sending_identity?:SendingIdentity; name:string; description:string|null; status:SequenceStatus; timezone:string; starts_at:string|null; allowed_weekdays:number[]; send_window_start:string; send_window_end:string; track_opens:boolean; track_clicks:boolean; stop_on_reply:boolean; steps:OutreachStep[]; enrollments_count:number; messages_count:number; activated_at:string|null; created_at:string; updated_at:string }
export interface OutreachEnrollment { id:string; company_id:string; sequence_id:string; sequence_name?:string; recipient_type:"CONTACT"|"LEAD"; recipient_id:string; recipient_email:string; recipient_name:string; status:string; current_step_position:number; next_action_at:string|null; enrolled_at:string; ended_at:string|null; messages_count:number }
export interface MessageEvent { id:string; type:string; occurred_at:string }
export interface OutreachMessage { id:string; company_id:string; enrollment_id:string; sequence_id:string; sequence_name?:string; sequence_step_id:string; sending_identity_id:string; provider_connection_id:string; template_id:string|null; recipient_type:string; recipient_id:string; to_email:string; to_name:string; from_email:string; from_name:string; subject:string; body_html:string|null; body_text:string; state:MessageState; scheduled_at:string; sent_at:string|null; delivered_at:string|null; bounced_at:string|null; failed_at:string|null; replied_at:string|null; failure_message:string|null; attempts_count:number; events?:MessageEvent[] }
export interface OutreachSuppression { id:string; company_id:string; email:string; reason:string; source:string; details:string|null; is_active:boolean; suppressed_at:string; removed_at:string|null }
export interface OutreachReport { sent:number; delivered:number; failed:number; bounced:number; replies:number; unsubscribes:number; complaints:number; opens:number; clicks:number; delivery_rate_bps:number; reply_rate_bps:number; open_rate_bps:number; click_rate_bps:number; by_sequence:Array<Record<string,unknown>>; by_template:Array<Record<string,unknown>>; by_sender:Array<Record<string,unknown>> }
export interface EnrollmentResult { enrolled:OutreachEnrollment[]; failures:Array<{recipient_id:string;message:string;error_code:string}> }
export interface Paginated<T> { data:T[]; meta?:{current_page:number;last_page:number;per_page:number;total:number}; current_page?:number; last_page?:number; per_page?:number; total?:number }
