<script setup lang="ts">
import { computed, ref } from "vue"; import { useRouter } from "vue-router";
import AppShell from "@/components/zs/AppShell.vue"; import PageHeader from "@/components/zs/PageHeader.vue"; import Panel from "@/components/zs/Panel.vue"; import SearchInput from "@/components/zs/SearchInput.vue"; import Toolbar from "@/components/zs/Toolbar.vue"; import PipelineBoard from "@/components/crm/PipelineBoard.vue"; import AsyncSection from "@/components/zs/AsyncSection.vue";
import { useCrmData } from "@/composables/useCrmData"; import { useMutation } from "@/composables/useAsyncData"; import { crmRepository } from "@/services/crm/repository"; import { showToast } from "@/composables/useToast"; import { setPageMeta } from "@/lib/page-meta";
setPageMeta("CRM Pipeline", "Manage opportunities across configurable sales pipelines.");
const data = useCrmData(); const router = useRouter(); const search = ref(""); const owner = ref("All owners"); const selectedPipelineId = ref("");
const pipelines = computed(() => data.pipelines.data.value ?? []); const selectedPipeline = computed(() => pipelines.value.find((item) => item.id === selectedPipelineId.value) ?? pipelines.value.find((item) => item.isDefault) ?? pipelines.value[0]);
const owners = computed(() => [...new Set((data.deals.data.value ?? []).map((item) => item.owner).filter(Boolean))]);
const deals = computed(() => (data.deals.data.value ?? []).filter((item) => (!selectedPipeline.value || item.pipelineId === selectedPipeline.value.id) && (owner.value === "All owners" || item.owner === owner.value) && `${item.name} ${item.company}`.toLowerCase().includes(search.value.toLowerCase())));
const moveMutation = useMutation((id: string, stageId: string, lossReason?: string) => crmRepository.transitionDeal(data.activeCompanyId.value, id, stageId, lossReason));
async function move(id: string, stageId: string) { const stage=selectedPipeline.value?.stages.find((item)=>item.id===stageId);const lossReason=stage?.isLost?window.prompt("Loss reason (required)")?.trim():undefined;if(stage?.isLost&&!lossReason)return;const saved = await moveMutation.run(id, stageId, lossReason); if (!saved) return; await Promise.all([data.deals.refresh(), data.dashboard.refresh()]); showToast("Stage updated", `Opportunity moved to ${saved.stage}.`, "success"); }
</script>
<template><AppShell><PageHeader title="Pipeline" description="Drag opportunities between configured stages"/><Panel><Toolbar><SearchInput v-model="search" placeholder="Search deal or company"/><select v-model="selectedPipelineId" class="field max-w-48"><option value="">Default pipeline</option><option v-for="pipeline in pipelines" :key="pipeline.id" :value="pipeline.id">{{ pipeline.name }}</option></select><select v-model="owner" class="field max-w-48"><option>All owners</option><option v-for="name in owners" :key="name">{{ name }}</option></select></Toolbar><AsyncSection :loading="data.deals.loading.value || data.pipelines.loading.value" :error="data.deals.error.value || data.pipelines.error.value || moveMutation.error.value" :empty="!selectedPipeline" empty-title="No pipeline configured" @retry="data.refresh"><div class="p-3"><PipelineBoard :deals="deals" :stages="selectedPipeline?.stages.filter((stage) => stage.isActive) ?? []" @move="move" @open="(id) => router.push(`/crm/deals/${id}`)"/></div></AsyncSection></Panel></AppShell></template>
