<script setup lang="ts">
import {computed,ref} from "vue";import {MailPlus,UserRoundCheck,UserRoundX} from "lucide-vue-next";
import AppShell from "@/components/zs/AppShell.vue";import PageHeader from "@/components/zs/PageHeader.vue";import Panel from "@/components/zs/Panel.vue";import DataTable,{type Column} from "@/components/zs/DataTable.vue";import SearchInput from "@/components/zs/SearchInput.vue";import Toolbar from "@/components/zs/Toolbar.vue";import ZButton from "@/components/zs/ZButton.vue";import StatusBadge from "@/components/zs/StatusBadge.vue";import SidePanel from "@/components/zs/SidePanel.vue";import Field from "@/components/zs/Field.vue";import ValidationMessage from "@/components/zs/ValidationMessage.vue";
import {useAsyncData,useMutation} from "@/composables/useAsyncData";import {platformRepository} from "@/services/platform/repository";import {useCompanyStore} from "@/stores/company";import {showToast} from "@/composables/useToast";import {setPageMeta} from "@/lib/page-meta";import type {CompanyMembership} from "@/types/platform";
setPageMeta("Users & Invitations","Administer company membership, invitations and role assignments.");
const company=useCompanyStore(),tab=ref<'Users'|'Invitations'>('Users'),query=ref(''),inviteOpen=ref(false),email=ref(''),roleId=ref('');
const users=useAsyncData(()=>platformRepository.users(company.activeCompanyId),{watch:[()=>company.activeCompanyId]});const invites=useAsyncData(()=>platformRepository.invitations(company.activeCompanyId),{watch:[()=>company.activeCompanyId]});const roles=useAsyncData(()=>platformRepository.roles(company.activeCompanyId),{watch:[()=>company.activeCompanyId]});
const rows=computed(()=>(users.data.value?.data??[]).filter(x=>`${x.user.name} ${x.user.email}`.toLowerCase().includes(query.value.toLowerCase())));const columns:Column[]=[{key:'user',header:'User'},{key:'roles',header:'Roles'},{key:'status',header:'Status'},{key:'actions',header:''}];
const invite=useMutation(async()=>{if(!roleId.value)throw new Error('Select a role.');return platformRepository.invite(company.activeCompanyId,email.value,[Number(roleId.value)])});
async function sendInvite(){const result=await invite.run();if(!result)return;showToast('Invitation sent',`Invitation created for ${email.value}.`);email.value='';inviteOpen.value=false;await invites.refresh()}
async function toggle(member:CompanyMembership){await platformRepository.updateMemberStatus(company.activeCompanyId,member.id,!member.is_active);showToast(member.is_active?'User suspended':'User reactivated');await users.refresh()}
async function remove(member:CompanyMembership){await platformRepository.removeMember(company.activeCompanyId,member.id);showToast('Membership removed');await users.refresh()}
async function assign(member:CompanyMembership,event:Event){const value=(event.target as HTMLSelectElement).value;await platformRepository.updateMemberRoles(company.activeCompanyId,member.id,value?[Number(value)]:[]);showToast('Role assignment updated');await users.refresh()}
async function revoke(id:string){await platformRepository.revokeInvitation(company.activeCompanyId,id);showToast('Invitation revoked');await invites.refresh()}
async function resend(id:string){await platformRepository.resendInvitation(company.activeCompanyId,id);showToast('Invitation resent');await invites.refresh()}
</script>
<template><AppShell><PageHeader title="Users & Invitations" description="Company-scoped access without changing a user's global identity"><template #actions><ZButton v-if="company.hasPermission('platform.invitations.manage')" @click="inviteOpen=true"><MailPlus class="size-4"/>Invite user</ZButton></template></PageHeader>
<div class="mb-4 flex gap-1 border-b border-line"><button v-for="item in ['Users','Invitations'] as const" :key="item" type="button" class="-mb-px border-b-2 px-3 py-2 text-sm" :class="tab===item?'border-primary font-medium text-content':'border-transparent text-content-secondary'" @click="tab=item">{{item}}</button></div>
<Panel v-if="tab==='Users'"><Toolbar><SearchInput v-model="query" placeholder="Search users"/></Toolbar><DataTable :columns="columns" :rows="rows" :min-width="900"><template #user="{row}:{row:CompanyMembership}"><p class="font-medium text-content">{{row.user.name}}</p><p class="text-2xs text-content-muted">{{row.user.email}}</p></template><template #roles="{row}:{row:CompanyMembership}"><select class="field w-48" :value="row.roles[0]?.id??row.role?.id??''" :disabled="!company.hasPermission('platform.users.manage')" @change="assign(row,$event)"><option value="">No role</option><option v-for="role in roles.data.value?.roles??[]" :key="role.id" :value="role.id">{{role.name}}</option></select></template><template #status="{row}:{row:CompanyMembership}"><StatusBadge :status="row.is_active?'active':'suspended'"/></template><template #actions="{row}:{row:CompanyMembership}"><div v-if="company.hasPermission('platform.users.manage')" class="flex justify-end gap-1"><ZButton variant="ghost" :disabled="row.user.id===company.currentUser.id" @click="toggle(row)"><component :is="row.is_active?UserRoundX:UserRoundCheck" class="size-4"/>{{row.is_active?'Suspend':'Reactivate'}}</ZButton><ZButton variant="ghost" :disabled="row.user.id===company.currentUser.id" @click="remove(row)">Remove</ZButton></div></template></DataTable></Panel>
<Panel v-else title="Pending and historical invitations"><div class="divide-y divide-line"><div v-for="item in invites.data.value?.data??[]" :key="item.id" class="flex flex-wrap items-center justify-between gap-3 px-4 py-3"><div><p class="text-sm font-medium text-content">{{item.email}}</p><p class="text-2xs text-content-muted">Expires {{new Date(item.expires_at).toLocaleString()}}</p></div><div class="flex items-center gap-2"><StatusBadge :status="item.status.toLowerCase()"/><ZButton v-if="item.status==='PENDING'&&company.hasPermission('platform.invitations.manage')" variant="ghost" @click="resend(item.id)">Resend</ZButton><ZButton v-if="item.status==='PENDING'&&company.hasPermission('platform.invitations.manage')" variant="ghost" @click="revoke(item.id)">Revoke</ZButton></div></div><p v-if="!invites.data.value?.data.length" class="p-6 text-center text-sm text-content-muted">No invitations.</p></div></Panel>
<SidePanel :open="inviteOpen" title="Invite a company user" description="The invitation expires after seven days." @close="inviteOpen=false"><form class="space-y-4" @submit.prevent="sendInvite"><Field v-model="email" label="Work email" type="email" required/><label class="block"><span class="label-caps">Role</span><select v-model="roleId" class="field mt-1.5 w-full" required><option value="">Select role</option><option v-for="role in roles.data.value?.roles??[]" :key="role.id" :value="String(role.id)">{{role.name}}</option></select></label><ValidationMessage :message="invite.error.value?.message"/><ZButton type="submit" :disabled="invite.saving.value">{{invite.saving.value?'Sending…':'Send invitation'}}</ZButton></form></SidePanel></AppShell></template>
