import { apiDownload,apiRequest } from "@/services/api/client";
import type { AuditRecord,CompanyExport,CompanyInvitation,CompanyMembership,CompanySettings,FailedJob,NotificationInbox,NotificationPreference,Paginated,PlatformDocument,PlatformNotification,PlatformRole,SecurityPayload,SubscriptionPayload } from "@/types/platform";

export const platformRepository={
 acceptInvitation:(token:string,input:{name?:string;password?:string})=>apiRequest<{already_accepted:boolean}>("/invitations/accept",{method:"POST",body:{...input,token}}),
 users:(companyId:string,search="")=>apiRequest<Paginated<CompanyMembership>>("/platform/users",{companyId,query:{search}}),
 invitations:(companyId:string)=>apiRequest<Paginated<CompanyInvitation>>("/platform/invitations",{companyId}),
 invite:(companyId:string,email:string,role_ids:number[])=>apiRequest<{invitation:CompanyInvitation}>("/platform/invitations",{method:"POST",companyId,body:{email,role_ids}}),
 resendInvitation:(companyId:string,id:string)=>apiRequest<{invitation:CompanyInvitation}>(`/platform/invitations/${id}/resend`,{method:"POST",companyId,body:{}}),
 revokeInvitation:(companyId:string,id:string)=>apiRequest<CompanyInvitation>(`/platform/invitations/${id}/revoke`,{method:"POST",companyId,body:{}}),
 updateMemberStatus:(companyId:string,id:number,active:boolean)=>apiRequest<CompanyMembership>(`/platform/users/${id}/status`,{method:"PATCH",companyId,body:{active}}),
 updateMemberRoles:(companyId:string,id:number,role_ids:number[])=>apiRequest<CompanyMembership>(`/platform/users/${id}/roles`,{method:"PUT",companyId,body:{role_ids}}),
 removeMember:(companyId:string,id:number)=>apiRequest<{message:string}>(`/platform/users/${id}`,{method:"DELETE",companyId}),
 roles:(companyId:string)=>apiRequest<{roles:PlatformRole[];permissions:Array<{id:number;name:string;description:string|null}>}>("/platform/roles",{companyId}),
 createRole:(companyId:string,input:{name:string;permission_ids:number[]})=>apiRequest<PlatformRole>("/platform/roles",{method:"POST",companyId,body:input}),
 updateRole:(companyId:string,id:number,input:{name:string;permission_ids:number[]})=>apiRequest<PlatformRole>(`/platform/roles/${id}`,{method:"PUT",companyId,body:input}),
 cloneRole:(companyId:string,id:number,name:string)=>apiRequest<PlatformRole>(`/platform/roles/${id}/clone`,{method:"POST",companyId,body:{name}}),
 archiveRole:(companyId:string,id:number)=>apiRequest<PlatformRole>(`/platform/roles/${id}/archive`,{method:"POST",companyId,body:{}}),
 settings:(companyId:string)=>apiRequest<CompanySettings>("/platform/settings",{companyId}),
 saveSettings:(companyId:string,input:Partial<CompanySettings>)=>apiRequest<CompanySettings>("/platform/settings",{method:"PUT",companyId,body:input}),
 uploadLogo:(companyId:string,file:File)=>{const body=new FormData();body.set('logo',file);return apiRequest<{settings:CompanySettings}>("/platform/settings/logo",{method:'POST',companyId,body})},
 createCompany:(input:{name:string;currency:string;timezone:string;country_code:string;plan_id:number})=>apiRequest<{company:{id:string}}>("/platform/companies",{method:'POST',body:input}),
 subscription:(companyId:string)=>apiRequest<SubscriptionPayload>("/platform/subscription",{companyId}),
 saveSubscription:(companyId:string,input:{plan_id:number;status:string;billing_interval:string;trial_ends_at?:string|null;renews_at?:string|null;ends_at?:string|null})=>apiRequest("/platform/subscription",{method:"PUT",companyId,body:input}),
 setEntitlement:(companyId:string,module:string,is_enabled:boolean)=>apiRequest(`/platform/entitlements/${module}`,{method:"PUT",companyId,body:{is_enabled}}),
 notifications:(companyId:string,signal?:AbortSignal,page=1)=>apiRequest<NotificationInbox>("/platform/notifications",{companyId,signal,query:{page}}),
 readNotification:(companyId:string,id:string,signal?:AbortSignal)=>apiRequest<PlatformNotification>(`/platform/notifications/${id}/read`,{method:"POST",companyId,body:{},signal}),
 readAllNotifications:(companyId:string,signal?:AbortSignal)=>apiRequest<{message:string}>("/platform/notifications/read-all",{method:"POST",companyId,body:{},signal}),
 notificationPreferences:(companyId:string,signal?:AbortSignal)=>apiRequest<NotificationPreference[]>("/platform/notification-preferences",{companyId,signal}),
 saveNotificationPreferences:(companyId:string,preferences:NotificationPreference[],signal?:AbortSignal)=>apiRequest<NotificationPreference[]>("/platform/notification-preferences",{method:"PUT",companyId,body:{preferences},signal}),
 documents:(companyId:string)=>apiRequest<Paginated<PlatformDocument>>("/platform/documents",{companyId}),
 uploadDocument:(companyId:string,input:{type:string;id:string;category:string;file:File})=>{const body=new FormData();body.set("documentable_type",input.type);body.set("documentable_id",input.id);body.set("category",input.category);body.set("file",input.file);return apiRequest<PlatformDocument>("/platform/documents",{method:"POST",companyId,body})},
 deleteDocument:(companyId:string,id:string)=>apiRequest<{message:string}>(`/platform/documents/${id}`,{method:"DELETE",companyId}),
 downloadDocument:(companyId:string,id:string,filename:string)=>apiDownload(`/platform/documents/${id}/download`,companyId,filename),
 audit:(companyId:string,query:Record<string,string>)=>apiRequest<Paginated<AuditRecord>>("/platform/audit",{companyId,query}),
 security:(companyId:string)=>apiRequest<SecurityPayload>("/platform/security",{companyId}),
 revokeSession:(companyId:string,id:string)=>apiRequest<{message:string}>(`/platform/security/sessions/${encodeURIComponent(id)}`,{method:"DELETE",companyId}),
 revokeOtherSessions:(companyId:string)=>apiRequest<{message:string}>("/platform/security/sessions",{method:"DELETE",companyId}),
 failedJobs:(companyId:string)=>apiRequest<Paginated<FailedJob>>("/platform/system/failed-jobs",{companyId}),
 retryJob:(companyId:string,uuid:string)=>apiRequest<{message:string}>(`/platform/system/failed-jobs/${uuid}/retry`,{method:"POST",companyId,body:{}}),
 exports:(companyId:string)=>apiRequest<Paginated<CompanyExport>>("/platform/exports",{companyId}),
 requestExport:(companyId:string,sections:string[])=>apiRequest<CompanyExport>("/platform/exports",{method:"POST",companyId,body:{sections}}),
 live:()=>apiRequest<{status:string}>("/health/live",{}),
 ready:()=>apiRequest<{status:string;checks:Record<string,boolean>}>("/health/ready",{}),
};
