import {test,expect,type Page} from '@playwright/test';
const domains=[['documents','documents','Documents'],['announcements','announcements','Announcements'],['directory','directory','Colleague directory'],['teams','my-teams','My Team'],['assets','asset-requests','Equipment requests'],['expenses','expense-claims','Expense claims'],['shift-swaps','shift-swaps','Shift swaps']] as const;
async function setup(page:Page,options:{permissions?:string[];modules?:string[];former?:boolean;hidden?:boolean;unlinked?:boolean}={}){
  const calls:{path:string;method:string;company:string;body:any;key?:string}[]=[];
  const permissions=options.permissions??['*'];
  const company=(id:string)=>({id,name:`Company ${id}`,timezone:'Asia/Karachi',modules:options.modules??['payroll'],permissions,roles:[],effective_navigation:{visible_keys:options.hidden?[]:['employee.profile',...domains.map(d=>'employee.'+(d[0]==='shift-swaps'?'shift_swaps':d[0])),'employee.schedule',...['employee_documents','announcements','teams','shifts','rotas','shift_swaps','asset_requests','expenses','expense_categories'].map(k=>'hrm.'+k)],items:[],catalog:[]}});
  const rows=new Map<string,any>();
  const make=(kind:string,id:string)=>({id:`${kind}-${id}`,version:1,status:kind==='announcements'?'DRAFT':kind==='expense-claims'?'DRAFT':kind==='shift-swaps'?'PENDING_TARGET':'PENDING',name:`Record ${id}`,full_name:`Colleague ${id}`,title:`Record ${id}`,description:`Private description ${id}`,original_filename:kind==='documents'||kind==='employee-documents'?`private-${id}.txt`:undefined,category:kind==='employee-documents'?'ISSUED':'PERSONAL',mime_type:'text/plain',size_bytes:8,released_at:null,member_count:1,lead:null,employee_id:'self',item_description:`Equipment ${id}`,reason:'Synthetic reason',target_employee_id:'self',from_assignment_id:'own-assignment',to_assignment_id:'target-assignment',amount_minor:12345,category_id:'category',expense_date:'2030-01-01',is_active:true,phone:'555-0100',relationship:'Family',attachment:null,receipt:null,events:[],start_date:'2030-01-01',end_date:'2030-01-05',start_time:'09:00',end_time:'17:00',timezone:'Asia/Karachi'});
  await page.route('**/api/v1/**',async route=>{
    const req=route.request(),url=new URL(req.url()),path=url.pathname,method=req.method(),id=req.headers()['x-company-id']??'A';const body=req.postData()&&!req.headers()['content-type']?.includes('multipart')?req.postDataJSON():{};calls.push({path,method,company:id,body,key:req.headers()['idempotency-key']});const reply=(json:unknown,status=200)=>route.fulfill({json,status});
    if(path.endsWith('/auth/me'))return reply({user:{id:1,name:'Account',email:'portal@example.invalid',is_platform_admin:true},companies:['A','B'].map(company)});
    if(path.endsWith('/auth/switch-company'))return reply({company:company(body.company_id)});
    if(path.endsWith('/auth/profile'))return reply({id:1,name:'Account',email:'portal@example.invalid',email_verified:true});
    if(path.endsWith('/employee/me'))return reply({linked:!options.unlinked,employee:options.unlinked?null:{id:'self',full_name:`Employee ${id}`,employee_code:'SELF',status:options.former?'terminated':'active',address:'Original address',self_profile_version:1},self_editable:!options.former});
    if(path.endsWith('/platform/notifications'))return reply({unread_count:0,notifications:{data:[],total:0,current_page:1,last_page:1}});
    const match=path.match(/^\/api\/v1\/(employee|hrm)\/([^/]+)(?:\/([^/]+))?(?:\/([^/]+))?(?:\/([^/]+))?$/);if(!match)return reply({message:'Unavailable'},403);
    const kind=match[2]!,recordId=match[3],action=match[4];if(options.unlinked&&match[1]==='employee')return reply({message:'No linked identity',error_code:'EMPLOYEE_IDENTITY_NOT_LINKED'},409);
    const key=kind+'-'+id;if(!rows.has(key))rows.set(key,make(kind,id));const row=rows.get(key);
    if(kind==='schedule')return reply({data:[{id:'own-assignment',shift_name:`Published shift ${id}`,shift_date:url.searchParams.get('from_date'),start_time:'09:00',end_time:'17:00',timezone:'Asia/Karachi',version:1,slot_id:'slot'}]});
    if(kind==='expense-categories')return reply({data:[{id:'category',name:'Travel',version:1,is_active:true}],meta:{total:1,current_page:1,last_page:1}});
    if(method==='GET'&&['download','attachment','receipt'].includes(action??''))return route.fulfill({body:'private',contentType:'text/plain'});
    if(method==='GET'&&recordId){if(kind==='my-teams'||kind==='teams')return reply({team:row,data:[{id:'member',full_name:'Certified member',department:'Design',designation:'Designer',location:'Lahore'}],meta:{total:1,current_page:1,last_page:1}});if(kind==='rotas')return reply({rota:{...row,status:'DRAFT'},slots:[{id:'slot',shift_date:'2030-01-02',start_time:'09:00',end_time:'17:00',required_coverage:2,assigned_count:1,coverage_gap:1,assignments:[{id:'assignment',employee_id:'explicit-employee',version:1}]}]});return reply(row);}
    if(method==='GET')return reply({data:[row],meta:{total:2,current_page:Number(url.searchParams.get('page')??1),last_page:2},manager:{id:'manager',full_name:'Certified manager',department:'Ops',designation:'Lead',location:'Lahore'},direct_report_count:1});
    if(action==='release')row.released_at='2030-01-01T10:00:00Z';
    if(action==='publish')row.status='PUBLISHED';if(action==='accept')row.status='PENDING_ADMIN';if(action==='decline')row.status='DECLINED';if(action==='approve')row.status='APPROVED';if(action==='reject')row.status='REJECTED';if(action==='submit')row.status='SUBMITTED';
    if(action==='receipt')row.receipt={id:'file',original_filename:'receipt.txt',mime_type:'text/plain',size_bytes:8};
    if(action==='attachment')row.attachment={id:'file',original_filename:'attachment.txt',mime_type:'text/plain',size_bytes:8};
    row.version++;Object.assign(row,body);return reply(row,recordId?200:201);
  });return {calls,rows};
}
async function open(page:Page,path:string){await page.goto(path);await page.getByRole('button',{name:'View details',exact:true}).first().click();}
for(const [route,api,title] of domains){
  test(`${route} list detail privacy pagination`,async({page})=>{const {calls}=await setup(page);await page.goto('/employee/'+route);await expect(page.getByRole('heading',{name:title,exact:true}).first()).toBeVisible();await expect(page.getByText('Page 1 of 2 · 2 records').first()).toBeVisible();await page.getByRole('button',{name:'Next page',exact:true}).first().click();await expect.poll(()=>calls.some(c=>c.path.endsWith('/employee/'+api))).toBeTruthy();await expect(page.getByText('Page 2 of 2 · 2 records').first()).toBeVisible();expect(calls.some(c=>/\/hrm\/|\/accounting\/|\/inventory\/|\/banking\//.test(c.path))).toBeFalsy();});
  for(const status of [403,404,500])test(`${route} list ${status} retry`,async({page})=>{await setup(page);let fail=true,count=0;await page.route(url=>url.pathname===`/api/v1/employee/${api}`,r=>{count++;return fail?r.fulfill({status,json:{message:'Safe list failure'}}):r.fallback();});await page.goto('/employee/'+route);await expect(page.getByRole('alert').filter({hasText:'Safe list failure'})).toBeVisible();await expect(page.getByText('No records returned.',{exact:true})).toHaveCount(0);fail=false;await page.getByRole('button',{name:'Retry list',exact:true}).click();await expect(page.getByText('Page 1 of 2 · 2 records').first()).toBeVisible();expect(count).toBe(2);});
  test(`${route} late list cannot cross company`,async({page})=>{await setup(page);let release=()=>{};const gate=new Promise<void>(r=>{release=r;});let started=false;await page.route(url=>url.pathname===`/api/v1/employee/${api}`,async r=>{if(r.request().headers()['x-company-id']==='A'){started=true;await gate;}await r.fallback().catch(()=>{});});await page.goto('/employee/'+route);await expect.poll(()=>started).toBe(true);await page.getByLabel('Active company').selectOption('B');release();await expect(page.getByText('Page 1 of 2 · 2 records').first()).toBeVisible();await expect(page.getByText('Private description A',{exact:true})).toHaveCount(0);});
  for(const width of [390,768,1440])test(`${route} layout and keyboard ${width}`,async({page})=>{await page.setViewportSize({width,height:900});await setup(page);await page.goto('/employee/'+route);await expect(page.getByRole('heading',{name:title,exact:true}).first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Next page',exact:true}).first().focus();await page.keyboard.press('Enter');await expect(page.getByText('Page 2 of 2 · 2 records').first()).toBeVisible();});
}
test('hidden navigation leaves direct route authorized',async({page})=>{await setup(page,{hidden:true});await page.goto('/employee/documents');await expect(page.getByRole('heading',{name:'Documents',exact:true})).toBeVisible();await expect(page.getByRole('navigation',{name:'Employee Portal',exact:true}).getByRole('link',{name:'Documents',exact:true})).toHaveCount(0);});
for(const options of [{permissions:['employee.self.view']},{modules:[]}])test(`platform admin no bypass ${JSON.stringify(options)}`,async({page})=>{const {calls}=await setup(page,options);await page.goto('/employee/documents');await expect(page).not.toHaveURL(/\/employee\/documents$/);expect(calls.some(c=>c.path.endsWith('/employee/documents'))).toBe(false);});
test('former employee may read documents but has no upload',async({page})=>{await setup(page,{former:true});await page.goto('/employee/documents');await expect(page.getByText('Page 1 of 2 · 2 records')).toBeVisible();await expect(page.getByRole('button',{name:'Upload document',exact:true})).toHaveCount(0);});
test('unlinked read shows explicit safe state',async({page})=>{await setup(page,{unlinked:true});await page.goto('/employee/documents');await expect(page.getByRole('alert').filter({hasText:'No employee profile is linked'})).toBeVisible();await expect(page.getByText('No records returned.',{exact:true})).toHaveCount(0);});
test('private document download and separate admin release',async({page})=>{const {calls}=await setup(page);await page.goto('/hrm/employee-documents');await page.getByLabel('Employee UUID',{exact:true}).fill('explicit');await page.getByRole('button',{name:'Load records',exact:true}).click();await page.getByRole('button',{name:'View details',exact:true}).click();await page.getByRole('button',{name:'Release to employee',exact:true}).click();await page.getByRole('button',{name:'Review submission',exact:true}).click();await expect(page.getByRole('alertdialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Review submission',exact:true})).toBeFocused();await page.getByRole('button',{name:'Review submission',exact:true}).click();await page.getByRole('button',{name:'Confirm operation',exact:true}).click();await expect(page.getByRole('button',{name:'Release to employee',exact:true})).toHaveCount(0);expect(calls.some(c=>c.path.endsWith('/employee/me'))).toBe(false);expect(calls.some(c=>c.method==='POST'&&c.path.endsWith('/release'))).toBe(true);});
test('expense exact money draft creation payload',async({page})=>{const {calls}=await setup(page);await page.goto('/employee/expenses');await page.getByRole('button',{name:'Create claim',exact:true}).click();await page.getByLabel('Expense category',{exact:true}).selectOption('category');await page.getByLabel('Title',{exact:true}).fill('Train ticket');await page.getByLabel('Amount (PKR)',{exact:true}).fill('123.45');await page.getByLabel('Expense date',{exact:true}).fill('2030-01-01');await page.getByRole('button',{name:'Review submission',exact:true}).click();await page.getByRole('button',{name:'Confirm operation',exact:true}).click();await expect.poll(()=>calls.filter(c=>c.method==='POST'&&c.path.endsWith('/expense-claims')).length).toBe(1);const c=calls.find(c=>c.method==='POST'&&c.path.endsWith('/expense-claims'))!;expect(c.body.amount_minor).toBe(12345);expect(c.key).toBeTruthy();expect(c.body).not.toHaveProperty('employee_id');});
test('uncertain upload retains exact File and key, switch clears it',async({page})=>{await setup(page);const uploads:{key?:string;body:string|null}[]=[];await page.route(url=>url.pathname==='/api/v1/employee/documents',r=>{if(r.request().method()!=='POST')return r.fallback();uploads.push({key:r.request().headers()['idempotency-key'],body:r.request().postData()});return r.abort('failed');});await page.goto('/employee/documents');await page.getByRole('button',{name:'Upload document',exact:true}).click();await page.getByLabel('File',{exact:true}).setInputFiles({name:'private.txt',mimeType:'text/plain',buffer:Buffer.from('original-content')});for(let n=0;n<2;n++){await page.getByRole('button',{name:n?'Retry same submission':'Review submission',exact:true}).click();await page.getByRole('button',{name:'Confirm operation',exact:true}).click();await expect.poll(()=>uploads.length).toBe(n+1);await expect(page.getByRole('button',{name:'Retry same submission',exact:true})).toBeEnabled();}expect(uploads[0]!.key).toBe(uploads[1]!.key);for(const v of uploads)expect(v.body).toContain('original-content');await page.getByLabel('Active company').selectOption('B');await expect(page.getByRole('button',{name:'Retry same submission',exact:true})).toHaveCount(0);await expect(page.getByLabel('File',{exact:true})).toHaveCount(0);});
test('swap target consent never offers administrative approval',async({page})=>{const {calls}=await setup(page);await open(page,'/employee/shift-swaps');await page.getByRole('button',{name:'Accept swap',exact:true}).click();await page.getByRole('button',{name:'Review submission',exact:true}).click();await page.getByRole('button',{name:'Confirm operation',exact:true}).click();await expect(page.getByText('PENDING_ADMIN',{exact:true}).first()).toBeVisible();await expect(page.getByRole('button',{name:'Approve exchange',exact:true})).toHaveCount(0);expect(calls.some(c=>c.method==='POST'&&c.path.endsWith('/approve'))).toBe(false);});
const adminDomains=[['employee-documents','Employee documents'],['announcements','Announcements'],['teams','Teams'],['shifts','Shifts'],['rotas','Rotas'],['shift-swaps','Shift swaps'],['asset-requests','Equipment requests'],['expenses','Expense claims'],['expense-categories','Expense categories']] as const;
for(const [path,title] of adminDomains)for(const width of [390,768,1440])test(`admin ${path} scoped keyboard layout ${width}`,async({page})=>{
  await page.setViewportSize({width,height:900});const {calls}=await setup(page);await page.goto('/hrm/'+path);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();
  if(path==='employee-documents'){await page.getByLabel('Employee UUID',{exact:true}).fill('explicit');await page.getByRole('button',{name:'Load records',exact:true}).focus();await page.keyboard.press('Enter');}
  await expect(page.getByText('Page 1 of 2 · 2 records').or(page.getByText('Page 1 of 1 · 1 records'))).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(calls.some(c=>c.path.includes('/employee/'))).toBe(false);
});
for(const width of [390,768,1440])test(`profile address and contacts keyboard ${width}`,async({page})=>{
  await page.setViewportSize({width,height:900});const {calls}=await setup(page);await page.goto('/employee/profile');await expect(page.getByLabel('Address',{exact:true})).toHaveValue('Original address');await page.getByLabel('Address',{exact:true}).fill('New self address');await page.getByRole('button',{name:'Save address',exact:true}).click();await expect.poll(()=>calls.some(c=>c.path.endsWith('/employee/me')&&c.method==='PATCH')).toBe(true);expect(calls.find(c=>c.method==='PATCH'&&c.path.endsWith('/employee/me'))!.body).toEqual({address:'New self address',version:1});
  await page.getByRole('button',{name:'Add contact',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Emergency person');await page.getByLabel('Relationship',{exact:true}).fill('Sibling');await page.getByLabel('Phone',{exact:true}).fill('555-0100');await page.getByRole('button',{name:'Review submission',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('alertdialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Review submission',exact:true})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
for(const width of [390,768,1440])test(`schedule company local dates and mobile ${width}`,async({page})=>{
  await page.setViewportSize({width,height:900});const {calls}=await setup(page);await page.goto('/employee/schedule');await page.getByLabel('From date',{exact:true}).fill('2030-02-01');await page.getByLabel('To date',{exact:true}).fill('2030-02-28');await page.getByRole('button',{name:'Load records',exact:true}).click();await expect(page.getByText('Published shift A',{exact:true}).first()).toBeVisible();await expect(page.getByText('Asia/Karachi',{exact:true}).first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(calls.some(c=>c.method!=='GET'&&c.path.includes('/attendance/'))).toBe(false);
});
test('stale document detail and download cannot cross company',async({page})=>{
  await setup(page);let release=()=>{};const gate=new Promise<void>(r=>{release=r;});let started=false;const downloads:string[]=[];page.on('download',d=>downloads.push(d.suggestedFilename()));await open(page,'/employee/documents');
  await page.route('**/employee/documents/documents-A/download',async r=>{started=true;await gate;await r.fulfill({body:'old private file'}).catch(()=>{});});await page.getByRole('button',{name:'Download private-A.txt',exact:true}).click();await expect.poll(()=>started).toBe(true);await page.getByLabel('Active company').selectOption('B');release();await expect(page.getByText('private-B.txt',{exact:true}).first()).toBeVisible();await expect(page.getByRole('button',{name:'Download private-A.txt',exact:true})).toHaveCount(0);expect(downloads).toEqual([]);
});
test('late category metadata cannot reopen old claim form',async({page})=>{
  await setup(page);let release=()=>{};const gate=new Promise<void>(r=>{release=r;});let started=false;await page.route(url=>url.pathname==='/api/v1/employee/expense-categories',async r=>{started=true;await gate;await r.fallback().catch(()=>{});});await page.goto('/employee/expenses');await page.getByRole('button',{name:'Create claim',exact:true}).click();await expect.poll(()=>started).toBe(true);await page.getByLabel('Active company').selectOption('B');release();await expect(page.getByLabel('Expense category',{exact:true})).toHaveCount(0);await expect(page.getByText('Private description A',{exact:true})).toHaveCount(0);
});
test('version conflict refreshes authoritative expense detail and does not retry automatically',async({page})=>{
  const {rows}=await setup(page);let attempts=0;await open(page,'/employee/expenses');await page.route('**/employee/expense-claims/expense-claims-A',r=>{if(r.request().method()!=='PATCH')return r.fallback();attempts++;Object.assign(rows.get('expense-claims-A'),{version:3,title:'Changed by server'});return r.fulfill({status:409,json:{message:'Claim changed',error_code:'EXPENSE_CLAIM_VERSION_STALE'}});});await page.getByRole('button',{name:'Edit draft',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('My change');await page.getByRole('button',{name:'Review submission',exact:true}).click();await page.getByRole('button',{name:'Confirm operation',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Claim changed'})).toBeVisible();await expect(page.getByText('Changed by server',{exact:true}).first()).toBeVisible();expect(attempts).toBe(1);await expect(page.getByLabel('Title',{exact:true})).toHaveCount(0);
});
test('safe server error remains text and cannot execute HTML',async({page})=>{
  await setup(page);await page.route(url=>url.pathname==='/api/v1/employee/documents',r=>r.fulfill({status:500,json:{message:'<img src=x onerror="window.finalLeak=true">'}}));await page.goto('/employee/documents');await expect(page.getByRole('alert').filter({hasText:'<img'})).toBeVisible();expect(await page.evaluate(()=>Reflect.get(window,'finalLeak'))).toBeUndefined();
});
test('asset double submission is locked and late mutation cannot affect new company',async({page})=>{
  await setup(page);let release=()=>{};const gate=new Promise<void>(r=>{release=r;});let attempts=0;await page.route(url=>url.pathname==='/api/v1/employee/asset-requests',async r=>{if(r.request().method()!=='POST')return r.fallback();attempts++;await gate;await r.fallback().catch(()=>{});});await page.goto('/employee/assets');await page.getByRole('button',{name:'Request equipment',exact:true}).click();await page.getByLabel('Equipment description',{exact:true}).fill('Keyboard');await page.getByLabel('Reason',{exact:true}).fill('Private old reason');await page.getByRole('button',{name:'Review submission',exact:true}).click();await page.getByRole('button',{name:'Confirm operation',exact:true}).click();await expect(page.getByRole('button',{name:'Working…',exact:true})).toBeDisabled();await expect.poll(()=>attempts).toBe(1);await page.getByLabel('Active company').selectOption('B');release();await expect(page.getByText('Equipment B',{exact:true}).first()).toBeVisible();await expect(page.getByLabel('Reason',{exact:true})).toHaveCount(0);await expect(page.getByText('Server confirmed the operation.',{exact:false})).toHaveCount(0);
});
for(const width of [390,768,1440])test(`Requests composition preserves statuses and mobile layout ${width}`,async({page})=>{await page.setViewportSize({width,height:900});const {calls}=await setup(page);await page.goto('/employee/requests');await expect(page.getByRole('heading',{name:'Requests',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Open Equipment requests',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Withdraw',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(calls.some(c=>c.method!=='GET')).toBe(false);});
