import { test, expect, type Page } from '@playwright/test';
type Kind='tasks'|'tickets';
type Options={permissions?:string[]; status?:string; former?:string; unlinked?:boolean; hidden?:boolean; modules?:string[]; labels?:boolean};
async function setup(page:Page,options:Options={}) {
  const calls:{path:string;method:string;company:string;body:Record<string,unknown>;key?:string}[]=[];
  const permissions=options.permissions??['employee.self.view','employee.tasks.view','employee.tasks.update','employee.tasks.comment','employee.tickets.view','employee.tickets.create','employee.tickets.comment','tasks.view','tasks.manage','tasks.assign','tickets.view','tickets.manage'];
  const company=(id:string)=>({id,name:`Company ${id}`,modules:options.modules??['payroll'],permissions,roles:[],timezone:'Asia/Karachi',effective_navigation:{visible_keys:options.hidden?[]:['employee.tasks','employee.tickets','hrm.tasks','hrm.tickets'],items:[],catalog:[]}});
  const records=new Map<string,Record<string,unknown>[]>();
  for(const id of ['A','B'])for(const kind of ['tasks','tickets'])records.set(`${id}-${kind}`,[{id:`${kind}-${id}`,title:kind==='tasks'?`Task ${id}`:undefined,subject:kind==='tickets'?`Ticket ${id}`:undefined,description:`Private ${kind} ${id}`,status:options.status??(kind==='tasks'?'ASSIGNED':'OPEN'),priority:'NORMAL',version:1,due_date:'2030-10-05',category:'Access',creator_name:options.labels?'Unavailable user':'Certified Creator',assignee_name:options.labels?'Unavailable employee':'Certified Assignee',created_at:'2030-10-01T10:00:00Z'}]);
  const comments=new Map<string,unknown[]>(),files=new Map<string,unknown[]>();
  await page.route('**/api/v1/**',async route=>{
    const req=route.request(),url=new URL(req.url()),path=url.pathname,method=req.method(),id=req.headers()['x-company-id']??'A';
    const body=req.postData()&&!req.headers()['content-type']?.includes('multipart')?req.postDataJSON() as Record<string,unknown>:{};
    calls.push({path,method,company:id,body,key:req.headers()['idempotency-key']});
    const respond=(json:unknown,status=200)=>route.fulfill({json,status});
    if(path.endsWith('/auth/me'))return respond({user:{id:1,name:'Account',email:'work@example.invalid',is_platform_admin:true},companies:['A','B'].map(company)});
    if(path.endsWith('/auth/switch-company'))return respond({company:company(String(body.company_id))});
    if(path.endsWith('/employee/me'))return respond({linked:!options.unlinked,employee:options.unlinked?null:{id:'self',full_name:'Self Identity',employee_code:'EMP',status:options.former??'active'},self_editable:false});
    if(path.endsWith('/platform/notifications'))return respond({unread_count:0,notifications:{data:[],current_page:1,last_page:1,total:0}});
    const match=path.match(/^\/api\/v1\/(?:employee\/)?(tasks|tickets)(?:\/([^/]+))?(?:\/([^/]+))?(?:\/([^/]+))?$/);
    if(!match)return respond({message:'Unrelated API unavailable'},403);
    if(options.unlinked&&path.includes('/employee/'))return respond({message:'Unlinked',error_code:'EMPLOYEE_IDENTITY_NOT_LINKED'},409);
    const kind=match[1] as Kind,itemId=match[2],action=match[3],document=match[4],rows=records.get(`${id}-${kind}`)!;
    if(!itemId&&method==='POST'){const row={...rows[0],...body,id:`created-${kind}`,status:kind==='tasks'?'ASSIGNED':'OPEN',version:1};rows.unshift(row);return respond(row,201);}
    if(!itemId){const data=rows.filter(row=>!url.searchParams.get('status')||row.status===url.searchParams.get('status'));return respond({data,meta:{total:data.length,current_page:Number(url.searchParams.get('page')??1),last_page:2}});}
    const row=rows.find(row=>row.id===itemId);if(!row)return respond({message:'Not found'},404);
    if(action==='comments'){const key=`${id}-${itemId}`;if(!comments.has(key))comments.set(key,[]);if(method==='POST'){const comment={id:'comment',body:body.body,author:'Certified Author',created_at:'2030-10-01T11:00:00Z'};comments.get(key)!.push(comment);return respond(comment,201);}return respond({data:comments.get(key)});}
    if(action==='attachments'){const key=`${id}-${itemId}`;if(!files.has(key))files.set(key,[]);if(document)return route.fulfill({body:'private evidence',contentType:'text/plain'});if(method==='POST'){const file={id:'file',original_filename:'proof.txt',size_bytes:16,created_at:'2030-10-01T11:00:00Z',mime_type:'text/plain'};files.get(key)!.push(file);return respond(file,201);}return respond({data:files.get(key)});}
    if(method==='POST'||method==='PATCH'){
      if(body.version!==row.version)return respond({message:'Reload stale work',error_code:'WORK_VERSION_STALE'},409);
      if(action==='assign')Object.assign(row,{assignee_name:'Reassigned Employee'});
      else if(method==='PATCH')Object.assign(row,body);
      else row.status=({start:'IN_PROGRESS',complete:'COMPLETED',cancel:'CANCELLED',resolve:'RESOLVED',close:'CLOSED',reopen:kind==='tasks'?'ASSIGNED':'OPEN'} as Record<string,string>)[action!];
      row.version=Number(row.version)+1;return respond(row);
    }
    return respond(row);
  });
  return {calls,records};
}
async function open(page:Page,kind:Kind,admin=false){await page.goto(`/${admin?'hrm':'employee'}/${kind}`);await page.getByRole('button',{name:kind==='tasks'?'View task':'View ticket',exact:true}).first().click();await expect(page.getByText(`Private ${kind} A`,{exact:true})).toBeVisible();}
async function create(page:Page,kind:Kind,admin=false){await page.getByRole('button',{name:kind==='tasks'?'Create task':'Create ticket',exact:true}).click();await page.getByLabel(kind==='tasks'?'Task title':'Subject',{exact:true}).fill('New work request');await page.getByLabel('Description',{exact:true}).fill('Please review this request');if(admin){await page.getByLabel('Due date',{exact:true}).fill('2030-10-10');await page.getByLabel('Assignee employee UUID',{exact:true}).fill('11111111-1111-4111-8111-111111111111');}}
async function action(page:Page,name:string,status:string){await page.getByRole('button',{name,exact:true}).click();await page.getByRole('button',{name:'Record action',exact:true}).click();await expect(page.getByTestId('work-detail-status')).toHaveText(status);}
for(const kind of ['tasks','tickets'] as const)test(`${kind} list detail filters pagination and privacy`,async({page})=>{
  const {calls}=await setup(page);await open(page,kind);await expect(page.getByTestId('work-detail-status')).toHaveText(kind==='tasks'?'ASSIGNED':'OPEN');await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByText('Page 2 of 2',{exact:true})).toBeVisible();await page.getByLabel('Status filter').selectOption(kind==='tasks'?'COMPLETED':'CLOSED');await page.getByRole('button',{name:'Filter',exact:true}).click();await expect(page.getByText(`No matching ${kind}.`)).toBeVisible();expect(calls.filter(c=>c.path.includes(`/${kind}`)).every(c=>c.path.includes(`/employee/${kind}`))).toBeTruthy();
});
for(const labels of [false,true])test(`task safe server labels ${labels}`,async({page})=>{await setup(page,{labels});await open(page,'tasks');await expect(page.getByText(`Created by ${labels?'Unavailable user':'Certified Creator'} · Assigned to ${labels?'Unavailable employee':'Certified Assignee'}`)).toBeVisible();});
test('task employee start complete and closed evidence controls',async({page})=>{const {calls}=await setup(page);await open(page,'tasks');await action(page,'start','IN PROGRESS');await action(page,'complete','COMPLETED');await expect(page.getByRole('button',{name:'Add comment',exact:true})).toHaveCount(0);await expect(page.getByLabel('Attachment file')).toHaveCount(0);expect(calls.filter(c=>c.method==='POST').map(c=>c.path)).toEqual(['/api/v1/employee/tasks/tasks-A/start','/api/v1/employee/tasks/tasks-A/complete']);});
for(const state of ['OPEN','IN_PROGRESS','RESOLVED'])test(`employee ticket close from ${state}`,async({page})=>{await setup(page,{status:state});await open(page,'tickets');await action(page,'close','CLOSED');await expect(page.getByRole('button',{name:'Add comment',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'reopen',exact:true})).toHaveCount(0);});
for(const kind of ['tasks','tickets'] as const)for(const former of ['resigned','terminated'])test(`${former} ${kind} historical read only`,async({page})=>{await setup(page,{former});await open(page,kind);for(const name of ['start','close','Add comment','Upload attachment','Create ticket'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);});
for(const kind of ['tasks','tickets'] as const)test(`${kind} unlinked explicit`,async({page})=>{await setup(page,{unlinked:true});await page.goto(`/employee/${kind}`);await expect(page.getByText('No employee identity is linked to this company membership.')).toBeVisible();});
for(const audience of ['employee','hrm'])for(const kind of ['tasks','tickets'] as const)test(`${audience} ${kind} platform admin does not bypass missing permission`,async({page})=>{const {calls}=await setup(page,{permissions:['employee.self.view']});await page.goto(`/${audience}/${kind}`);await expect(page).toHaveURL(/\/$/);expect(calls.filter(c=>c.path.endsWith(`/${kind}`))).toHaveLength(0);});
for(const audience of ['employee','hrm'])test(`${audience} direct route hidden but permission allowed`,async({page})=>{
  await setup(page,{hidden:true});
  await open(page,'tasks',audience==='hrm');
  const path = `/${audience}/tasks`;
  await expect(page).toHaveURL(new RegExp(`${path}$`));
  // Visibility controls the sidebar item, not the authorized current-page breadcrumb.
  const sidebar = page.getByRole('complementary').getByRole('navigation');
  await expect(sidebar.locator(`a[href="${path}"]`)).toHaveCount(0);
  if (audience === 'hrm') {
    await expect(page.getByRole('navigation',{name:'Breadcrumb'}).getByRole('link',{name:'Tasks',exact:true})).toHaveAttribute('href','/hrm/tasks');
  }
});
test('entitlement cannot be replaced by navigation show',async({page})=>{const {calls}=await setup(page,{modules:[]});await page.goto('/employee/tasks');await expect(page).toHaveURL(/\/$/);expect(calls.filter(c=>c.path.includes('/employee/tasks'))).toHaveLength(0);});
for(const kind of ['tasks','tickets'] as const)test(`${kind} comments private files and domain firewall`,async({page})=>{const {calls}=await setup(page);await open(page,kind);await page.getByLabel('Comment',{exact:true}).fill('Shared update');await page.getByRole('button',{name:'Add comment',exact:true}).click();await expect(page.getByText('Shared update',{exact:true})).toBeVisible();await expect(page.getByText('Certified Author',{exact:false})).toBeVisible();await page.getByLabel('Attachment file').setInputFiles({name:'proof.txt',mimeType:'text/plain',buffer:Buffer.from('private evidence')});await page.getByRole('button',{name:'Upload attachment',exact:true}).click();await expect(page.getByText('Attachment uploaded.',{exact:true})).toBeVisible();const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'proof.txt',exact:true}).click();expect((await downloaded).suggestedFilename()).toBe('proof.txt');const writes=calls.filter(c=>c.method==='POST');expect(writes).toHaveLength(2);for(const write of writes){expect(write.path).toContain(`/employee/${kind}/`);expect(write.key).toBeTruthy();expect(write.body).not.toHaveProperty('employee_id');}});
for(const kind of ['tasks','tickets'] as const)for(const endpoint of ['comments','attachments'])test(`${kind} uncertain ${endpoint} retains same content and key`,async({page})=>{await setup(page);const attempts:{key:string|undefined;body:string|null}[]=[];await page.route(`**/employee/${kind}/*/${endpoint}`,route=>{if(route.request().method()!=='POST')return route.fallback();attempts.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});return attempts.length===1?route.abort('failed'):route.fallback();});await open(page,kind);if(endpoint==='comments'){await page.getByLabel('Comment',{exact:true}).fill('Retry body');await page.getByRole('button',{name:'Add comment',exact:true}).click();await expect(page.getByLabel('Comment',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Retry same comment',exact:true}).click();await expect(page.getByText('Comment recorded.',{exact:true})).toBeVisible();expect(attempts[1].body).toBe(attempts[0].body);}else{await page.getByLabel('Attachment file').setInputFiles({name:'proof.txt',mimeType:'text/plain',buffer:Buffer.from('private evidence')});await page.getByRole('button',{name:'Upload attachment',exact:true}).click();await expect(page.getByLabel('Attachment file')).toBeDisabled();await page.getByRole('button',{name:'Retry same upload',exact:true}).click();await expect(page.getByText('Attachment uploaded.',{exact:true})).toBeVisible();expect(attempts.every(a=>a.body?.includes('private evidence'))).toBeTruthy();}expect(attempts).toHaveLength(2);expect(attempts[1].key).toBe(attempts[0].key);});
for(const kind of ['tasks','tickets'] as const)test(`${kind} conflict reload and invalid transition`,async({page})=>{await setup(page);await page.route(`**/employee/${kind}/*/${kind==='tasks'?'start':'close'}`,route=>route.fulfill({status:409,json:{message:'This transition is stale or invalid',error_code:'WORK_VERSION_STALE'}}));await open(page,kind);await page.getByRole('button',{name:kind==='tasks'?'start':'close',exact:true}).click();await page.getByRole('button',{name:'Record action',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'This transition is stale or invalid'})).toBeVisible();await expect(page.getByTestId('work-detail-status')).toHaveText(kind==='tasks'?'ASSIGNED':'OPEN');});
for(const admin of [false,true])test(`${admin?'admin task':'employee ticket'} uncertain creation and double submit`,async({page})=>{await setup(page);const kind=admin?'tasks':'tickets';const attempts:{body:unknown;key?:string}[]=[];let release=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});await page.route(`**/api/v1/${admin?'':'employee/'}${kind}`,async route=>{if(route.request().method()!=='POST')return route.fallback();attempts.push({body:route.request().postDataJSON(),key:route.request().headers()['idempotency-key']});if(attempts.length===1){await gate;return route.abort('failed');}return route.fallback();});await page.goto(`/${admin?'hrm':'employee'}/${kind}`);await create(page,kind,admin);await page.getByRole('button',{name:'Submit creation',exact:true}).click();await expect(page.getByRole('button',{name:'Retry same creation',exact:true})).toBeDisabled();expect(attempts).toHaveLength(1);release();await expect(page.getByRole('alert').filter({hasText:'Could not reach'})).toBeVisible();await page.getByRole('button',{name:'Retry same creation',exact:true}).click();await expect(page.getByText('Server state updated.',{exact:true})).toBeVisible();expect(attempts).toHaveLength(2);expect(attempts[1]).toEqual(attempts[0]);});
test('admin task content reassign reopen cancel without self identity calls',async({page})=>{const {calls}=await setup(page,{permissions:['tasks.view','tasks.manage','tasks.assign']});await open(page,'tasks',true);await page.getByRole('button',{name:'Edit task',exact:true}).click();await page.getByLabel('Task title',{exact:true}).fill('Updated title');await page.getByRole('button',{name:'Save task',exact:true}).click();await expect(page.getByRole('heading',{name:'Updated title',exact:true}).last()).toBeVisible();await page.getByLabel('New assignee employee UUID',{exact:true}).fill('22222222-2222-4222-8222-222222222222');await page.getByRole('button',{name:'Reassign task',exact:true}).click();await expect(page.getByText('Created by Certified Creator · Assigned to Reassigned Employee')).toBeVisible();await action(page,'start','IN PROGRESS');await action(page,'complete','COMPLETED');await action(page,'reopen','ASSIGNED');await action(page,'cancel','CANCELLED');expect(calls.some(c=>c.path.endsWith('/employee/me'))).toBeFalsy();expect(calls.filter(c=>c.method!=='GET').every(c=>c.path.startsWith('/api/v1/tasks'))).toBeTruthy();});
test('admin tickets lifecycle and employee visible comments attachments',async({page})=>{await setup(page,{permissions:['tickets.view','tickets.manage']});await open(page,'tickets',true);await page.getByLabel('Comment',{exact:true}).fill('Support response');await page.getByRole('button',{name:'Add comment',exact:true}).click();await expect(page.getByText('Support response',{exact:true})).toBeVisible();await page.getByLabel('Attachment file').setInputFiles({name:'proof.txt',mimeType:'text/plain',buffer:Buffer.from('private evidence')});await page.getByRole('button',{name:'Upload attachment',exact:true}).click();await expect(page.getByText('Attachment uploaded.',{exact:true})).toBeVisible();await action(page,'start','IN PROGRESS');await action(page,'resolve','RESOLVED');await action(page,'close','CLOSED');await action(page,'reopen','OPEN');});
for(const permission of ['tasks.manage','tasks.assign'])test(`admin separates ${permission}`,async({page})=>{await setup(page,{permissions:['tasks.view',permission]});await open(page,'tasks',true);await expect(page.getByRole('button',{name:'Create task',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Edit task',exact:true})).toHaveCount(permission==='tasks.manage'?1:0);await expect(page.getByRole('button',{name:'Reassign task',exact:true})).toHaveCount(permission==='tasks.assign'?1:0);});
for(const width of [390,768,1440])for(const kind of ['tasks','tickets'] as const)test(`${kind} responsive keyboard dialog ${width}`,async({page})=>{await page.setViewportSize({width,height:900});await setup(page);await open(page,kind);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();const control=page.getByRole('button',{name:kind==='tasks'?'start':'close',exact:true});await control.focus();await page.keyboard.press('Enter');await expect(page.getByRole('alertdialog')).toBeVisible();await page.keyboard.press('Escape');await expect(control).toBeFocused();});
for(const kind of ['tasks','tickets'] as const)for(const channel of ['list','detail','comments','attachments','transition'])test(`${kind} late ${channel} cannot cross company`,async({page})=>{await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});const suffix=channel==='list'?'':channel==='detail'?`/${kind}-A`:channel==='transition'?`/${kind}-A/${kind==='tasks'?'start':'close'}`:`/${kind}-A/${channel}`;await page.route(`**/api/v1/employee/${kind}${suffix}`,async route=>{if(route.request().headers()['x-company-id']==='A'){await gate;await route.fallback().catch(()=>{});}else await route.fallback();});await page.goto(`/employee/${kind}`);if(channel!=='list'){await page.getByRole('button',{name:kind==='tasks'?'View task':'View ticket',exact:true}).click();if(channel==='transition'){await page.getByRole('button',{name:kind==='tasks'?'start':'close',exact:true}).click();await page.getByRole('button',{name:'Record action',exact:true}).click();}}await page.getByLabel('Active company').selectOption('B');release();await expect(page.getByRole('heading',{name:kind==='tasks'?'Task B':'Ticket B',exact:true})).toBeVisible();await expect(page.getByText(`Private ${kind} A`,{exact:true})).toHaveCount(0);await expect(page.getByRole('alertdialog')).toHaveCount(0);});
test('safe error text never executes HTML',async({page})=>{await setup(page);await page.route('**/employee/tasks/tasks-A',route=>route.fulfill({status:404,json:{message:'<img src=x onerror="window.workLeak=true">'}}));await page.goto('/employee/tasks');await page.getByRole('button',{name:'View task',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'<img'})).toBeVisible();expect(await page.evaluate(()=>Reflect.get(window,'workLeak'))).toBeUndefined();await expect(page.getByRole('button',{name:'start',exact:true})).toHaveCount(0);});
for(const kind of ['tasks','tickets'] as const)for(const endpoint of ['comments','attachments'])test(`${kind} late ${endpoint} mutation is fenced and double submit disabled`,async({page})=>{
  await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});let attempts=0;
  await page.route(`**/employee/${kind}/*/${endpoint}`,async route=>{if(route.request().method()!=='POST')return route.fallback();attempts++;await gate;await route.fallback().catch(()=>{});});
  await open(page,kind);
  if(endpoint==='comments'){await page.getByLabel('Comment',{exact:true}).fill('Private old comment');await page.getByRole('button',{name:'Add comment',exact:true}).click();await expect(page.getByRole('button',{name:'Retry same comment',exact:true})).toBeDisabled();}
  else{await page.getByLabel('Attachment file').setInputFiles({name:'proof.txt',mimeType:'text/plain',buffer:Buffer.from('private evidence')});await page.getByRole('button',{name:'Upload attachment',exact:true}).click();await expect(page.getByRole('button',{name:'Retry same upload',exact:true})).toBeDisabled();}
  await expect.poll(()=>attempts).toBe(1);await page.getByLabel('Active company').selectOption('B');release();await expect(page.getByRole('heading',{name:kind==='tasks'?'Task B':'Ticket B',exact:true})).toBeVisible();await expect(page.getByText('Private old comment',{exact:true})).toHaveCount(0);await expect(page.getByText(endpoint==='comments'?'Comment recorded.':'Attachment uploaded.',{exact:true})).toHaveCount(0);
});
test('late private download is aborted on company switch',async({page})=>{
  await setup(page);await open(page,'tasks');await page.getByLabel('Attachment file').setInputFiles({name:'proof.txt',mimeType:'text/plain',buffer:Buffer.from('private evidence')});await page.getByRole('button',{name:'Upload attachment',exact:true}).click();await expect(page.getByRole('button',{name:'proof.txt',exact:true})).toBeVisible();
  let release=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});let requested=false;const downloads:string[]=[];page.on('download',d=>downloads.push(d.suggestedFilename()));
  await page.route('**/employee/tasks/tasks-A/attachments/file',async route=>{requested=true;await gate;await route.fulfill({body:'old private data',contentType:'text/plain'}).catch(()=>{});});
  await page.getByRole('button',{name:'proof.txt',exact:true}).click();await expect.poll(()=>requested).toBe(true);await page.getByLabel('Active company').selectOption('B');release();await expect(page.getByRole('heading',{name:'Task B',exact:true})).toBeVisible();await page.getByRole('button',{name:'View task',exact:true}).click();await expect(page.getByText('Private tasks B',{exact:true})).toBeVisible();expect(downloads).toEqual([]);
});
test('company switch clears uncertain creation key form and navigation',async({page})=>{
  const {calls}=await setup(page);let failed=false;
  await page.route('**/employee/tickets',route=>{if(route.request().method()==='POST'&&!failed){failed=true;return route.abort('failed');}return route.fallback();});
  await page.goto('/employee/tickets');await create(page,'tickets');await page.getByRole('button',{name:'Submit creation',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Could not reach'})).toBeVisible();
  await page.route('**/auth/switch-company',route=>route.fulfill({json:{company:{id:'B',name:'Company B',modules:['payroll'],permissions:['employee.self.view','employee.tickets.view','employee.tickets.create'],roles:[],effective_navigation:{visible_keys:[],items:[],catalog:[]}}}}));
  await page.getByLabel('Active company').selectOption('B');await expect(page.getByRole('heading',{name:'Ticket B',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Retry same creation',exact:true})).toHaveCount(0);await expect(page.getByLabel('Subject',{exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'My Tickets',exact:true})).toHaveCount(0);expect(calls.filter(c=>c.method==='POST'&&c.path.endsWith('/employee/tickets'))).toHaveLength(0);
});
for(const kind of ['tasks','tickets'] as const)test(`${kind} transition double submit is disabled`,async({page})=>{
  await setup(page);let release=()=>{};const gate=new Promise<void>(resolve=>{release=resolve;});let count=0;const command=kind==='tasks'?'start':'close';
  await page.route(`**/employee/${kind}/*/${command}`,async route=>{count++;await gate;return route.fallback();});await open(page,kind);await page.getByRole('button',{name:command,exact:true}).click();await page.getByRole('button',{name:'Record action',exact:true}).click();await expect(page.getByRole('button',{name:'Working…',exact:true})).toBeDisabled();await expect.poll(()=>count).toBe(1);release();await expect(page.getByTestId('work-detail-status')).toHaveText(kind==='tasks'?'IN PROGRESS':'CLOSED');expect(count).toBe(1);
});
for(const width of [390,768,1440])test(`admin task form at ${width}`,async({page})=>{await page.setViewportSize({width,height:900});await setup(page,{permissions:['tasks.view','tasks.manage','tasks.assign']});await page.goto('/hrm/tasks');await create(page,'tasks',true);await page.getByLabel('Priority',{exact:true}).selectOption('HIGH');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByLabel('Description',{exact:true}).focus();await page.keyboard.press('Tab');await expect(page.getByRole('button',{name:'Submit creation',exact:true})).toBeFocused();});
test('missing task labels show unavailable without identity inference',async({page})=>{const {calls}=await setup(page,{permissions:['tasks.view']});await page.route('**/api/v1/tasks/tasks-A',route=>route.fulfill({json:{id:'tasks-A',title:'Missing labels',description:'Narrow task',status:'ASSIGNED',priority:'NORMAL',version:1,due_date:'2030-10-05'}}));await page.goto('/hrm/tasks');await page.getByRole('button',{name:'View task',exact:true}).click();await expect(page.getByText('Created by Label unavailable · Assigned to Label unavailable')).toBeVisible();expect(calls.some(c=>c.path.includes('/employee/me')||c.path.includes('/users'))).toBeFalsy();});
for(const status of [403,404,500])test(`safe list failure ${status} supports retry`,async({page})=>{
  await setup(page);
  let fail = true, listRequests = 0;
  const listURL = (url: URL) => url.pathname === '/api/v1/employee/tickets';
  await page.route(listURL,route=>{
    if (route.request().method() !== 'GET') return route.fallback();
    listRequests++;
    return fail ? route.fulfill({status,json:{message:'Work cannot be read'}}) : route.fallback();
  });
  const failure = page.waitForResponse(response => listURL(new URL(response.url())) && response.request().method() === 'GET' && response.status() === status);
  await page.goto('/employee/tickets');
  expect((await failure).status()).toBe(status);
  const alert = page.getByRole('alert').filter({hasText:'Work cannot be read'});
  await expect(alert).toBeVisible();
  await expect(page.getByRole('heading',{name:'Ticket A',exact:true})).toHaveCount(0);
  await expect(page.getByText('No matching tickets.',{exact:true})).toHaveCount(0);
  expect(listRequests).toBe(1);
  fail = false;
  const retried = page.waitForResponse(response => listURL(new URL(response.url())) && response.request().method() === 'GET' && response.status() === 200);
  await page.getByRole('button',{name:'Retry list',exact:true}).click();
  expect((await retried).status()).toBe(200);
  await expect(page.getByRole('heading',{name:'Ticket A',exact:true})).toBeVisible();
  await expect(alert).toHaveCount(0);
  expect(listRequests).toBe(2);
});
